# coding: utf-8

"""
    Selling Partner API for Supply Sources

    Manage configurations and capabilities of seller supply sources.  # noqa: E501

    OpenAPI spec version: 2020-07-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.operating_hour import OperatingHour  # noqa: E501
from swagger_client.rest import ApiException


class TestOperatingHour(unittest.TestCase):
    """OperatingHour unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperatingHour(self):
        """Test OperatingHour"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.operating_hour.OperatingHour()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
