# coding: utf-8

"""
    Selling Partner API for A+ Content Management

    Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.  # noqa: E501

    OpenAPI spec version: 2020-11-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.standard_four_image_text_quadrant_module import StandardFourImageTextQuadrantModule  # noqa: E501
from swagger_client.rest import ApiException


class TestStandardFourImageTextQuadrantModule(unittest.TestCase):
    """StandardFourImageTextQuadrantModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStandardFourImageTextQuadrantModule(self):
        """Test StandardFourImageTextQuadrantModule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.standard_four_image_text_quadrant_module.StandardFourImageTextQuadrantModule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
