# coding: utf-8

"""
    Selling Partner API for FBA Inbound Eligibilty

    With the FBA Inbound Eligibility API, you can build applications that let sellers get eligibility previews for items before shipping them to Amazon's fulfillment centers. With this API you can find out if an item is eligible for inbound shipment to Amazon's fulfillment centers in a specific marketplace. You can also find out if an item is eligible for using the manufacturer barcode for FBA inventory tracking. Sellers can use this information to inform their decisions about which items to ship Amazon's fulfillment centers.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.fba_inbound_api import FbaInboundApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFbaInboundApi(unittest.TestCase):
    """FbaInboundApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.fba_inbound_api.FbaInboundApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_item_eligibility_preview(self):
        """Test case for get_item_eligibility_preview

        """
        pass


if __name__ == '__main__':
    unittest.main()