# coding: utf-8

"""
    The Selling Partner API for CustomerFeedback

    The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.  # noqa: E501

    OpenAPI spec version: 2024-06-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customer_feedback_api import CustomerFeedbackApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomerFeedbackApi(unittest.TestCase):
    """CustomerFeedbackApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.customer_feedback_api.CustomerFeedbackApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_browse_node_return_topics(self):
        """Test case for get_browse_node_return_topics

        """
        pass

    def test_get_browse_node_return_trends(self):
        """Test case for get_browse_node_return_trends

        """
        pass

    def test_get_browse_node_review_topics(self):
        """Test case for get_browse_node_review_topics

        """
        pass

    def test_get_browse_node_review_trends(self):
        """Test case for get_browse_node_review_trends

        """
        pass

    def test_get_item_browse_node(self):
        """Test case for get_item_browse_node

        """
        pass

    def test_get_item_review_topics(self):
        """Test case for get_item_review_topics

        """
        pass

    def test_get_item_review_trends(self):
        """Test case for get_item_review_trends

        """
        pass


if __name__ == '__main__':
    unittest.main()