# coding: utf-8

"""
    The Selling Partner API for CustomerFeedback

    The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.  # noqa: E501

    OpenAPI spec version: 2024-06-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.item_review_trends_response import ItemReviewTrendsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestItemReviewTrendsResponse(unittest.TestCase):
    """ItemReviewTrendsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemReviewTrendsResponse(self):
        """Test ItemReviewTrendsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.item_review_trends_response.ItemReviewTrendsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
