# coding: utf-8

"""
    Selling Partner API for Listings Restrictions

    The Selling Partner API for Listings Restrictions provides programmatic access to restrictions on Amazon catalog listings.  For more information, see the [Listings Restrictions API Use Case Guide](doc:listings-restrictions-api-v2021-08-01-use-case-guide).  # noqa: E501

    OpenAPI spec version: 2021-08-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.listings_api import ListingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestListingsApi(unittest.TestCase):
    """ListingsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.listings_api.ListingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_listings_restrictions(self):
        """Test case for get_listings_restrictions

        """
        pass


if __name__ == '__main__':
    unittest.main()