# coding: utf-8

"""
    Selling Partner API for Listings Restrictions

    The Selling Partner API for Listings Restrictions provides programmatic access to restrictions on Amazon catalog listings.  For more information, see the [Listings Restrictions API Use Case Guide](doc:listings-restrictions-api-v2021-08-01-use-case-guide).  # noqa: E501

    OpenAPI spec version: 2021-08-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.reason import Reason  # noqa: E501
from swagger_client.rest import ApiException


class TestReason(unittest.TestCase):
    """Reason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReason(self):
        """Test Reason"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.reason.Reason()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
