# coding: utf-8

"""
    Selling Partner API for Tokens 

    The Selling Partner API for Tokens provides a secure way to access a customer's PII (Personally Identifiable Information). You can call the Tokens API to get a Restricted Data Token (RDT) for one or more restricted resources that you specify. The RDT authorizes subsequent calls to restricted operations that correspond to the restricted resources that you specified.  For more information, see the [Tokens API Use Case Guide](doc:tokens-api-use-case-guide).  # noqa: E501

    OpenAPI spec version: 2021-03-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.restricted_resource import RestrictedResource  # noqa: E501
from swagger_client.rest import ApiException


class TestRestrictedResource(unittest.TestCase):
    """RestrictedResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRestrictedResource(self):
        """Test RestrictedResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.restricted_resource.RestrictedResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
