# coding: utf-8

"""
    Selling Partner API for Direct Fulfillment Orders

    The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.  # noqa: E501

    OpenAPI spec version: 2021-12-28
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.scheduled_delivery_shipment import ScheduledDeliveryShipment  # noqa: E501
from swagger_client.rest import ApiException


class TestScheduledDeliveryShipment(unittest.TestCase):
    """ScheduledDeliveryShipment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduledDeliveryShipment(self):
        """Test ScheduledDeliveryShipment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.scheduled_delivery_shipment.ScheduledDeliveryShipment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
