# coding: utf-8

"""
    Selling Partner API for Catalog Items

    Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).  # noqa: E501

    OpenAPI spec version: 2022-04-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.catalog_api import CatalogApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.catalog_api.CatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_catalog_item(self):
        """Test case for get_catalog_item

        """
        pass

    def test_search_catalog_items(self):
        """Test case for search_catalog_items

        """
        pass


if __name__ == '__main__':
    unittest.main()