# coding: utf-8

"""
    Selling Partner API for Catalog Items

    Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).  # noqa: E501

    OpenAPI spec version: 2022-04-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.item_identifiers_by_marketplace import ItemIdentifiersByMarketplace  # noqa: E501
from swagger_client.rest import ApiException


class TestItemIdentifiersByMarketplace(unittest.TestCase):
    """ItemIdentifiersByMarketplace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemIdentifiersByMarketplace(self):
        """Test ItemIdentifiersByMarketplace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.item_identifiers_by_marketplace.ItemIdentifiersByMarketplace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
