# coding: utf-8

"""
    Selling Partner API for Data Kiosk

    The Selling Partner API for Data Kiosk lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses.  # noqa: E501

    OpenAPI spec version: 2023-11-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_queries_response_pagination import GetQueriesResponsePagination  # noqa: E501
from swagger_client.rest import ApiException


class TestGetQueriesResponsePagination(unittest.TestCase):
    """GetQueriesResponsePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetQueriesResponsePagination(self):
        """Test GetQueriesResponsePagination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_queries_response_pagination.GetQueriesResponsePagination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
