# coding: utf-8

"""
    Selling Partner API for Product Fees

    The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.fees_api import FeesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFeesApi(unittest.TestCase):
    """FeesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.fees_api.FeesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_my_fees_estimate_for_asin(self):
        """Test case for get_my_fees_estimate_for_asin

        """
        pass

    def test_get_my_fees_estimate_for_sku(self):
        """Test case for get_my_fees_estimate_for_sku

        """
        pass

    def test_get_my_fees_estimates(self):
        """Test case for get_my_fees_estimates

        """
        pass


if __name__ == '__main__':
    unittest.main()