# coding: utf-8

"""
    The Selling Partner API for Amazon Seller Wallet Open Banking API

    The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.  # noqa: E501

    OpenAPI spec version: 2024-03-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PayeeContactInformation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payee_first_name': 'str',
        'payee_middle_name': 'str',
        'payee_last_name': 'str',
        'address_line1': 'str',
        'address_line2': 'str',
        'city': 'str',
        'state': 'str',
        'postal_code': 'str',
        'country': 'str',
        'country_code': 'str',
        'email_address': 'str',
        'phone_number': 'str',
        'payee_entity_type': 'PayeeEntityType'
    }

    attribute_map = {
        'payee_first_name': 'payeeFirstName',
        'payee_middle_name': 'payeeMiddleName',
        'payee_last_name': 'payeeLastName',
        'address_line1': 'addressLine1',
        'address_line2': 'addressLine2',
        'city': 'city',
        'state': 'state',
        'postal_code': 'postalCode',
        'country': 'country',
        'country_code': 'countryCode',
        'email_address': 'emailAddress',
        'phone_number': 'phoneNumber',
        'payee_entity_type': 'payeeEntityType'
    }

    def __init__(self, payee_first_name=None, payee_middle_name=None, payee_last_name=None, address_line1=None, address_line2=None, city=None, state=None, postal_code=None, country=None, country_code=None, email_address=None, phone_number=None, payee_entity_type=None):  # noqa: E501
        """PayeeContactInformation - a model defined in Swagger"""  # noqa: E501

        self._payee_first_name = None
        self._payee_middle_name = None
        self._payee_last_name = None
        self._address_line1 = None
        self._address_line2 = None
        self._city = None
        self._state = None
        self._postal_code = None
        self._country = None
        self._country_code = None
        self._email_address = None
        self._phone_number = None
        self._payee_entity_type = None
        self.discriminator = None

        self.payee_first_name = payee_first_name
        if payee_middle_name is not None:
            self.payee_middle_name = payee_middle_name
        self.payee_last_name = payee_last_name
        self.address_line1 = address_line1
        if address_line2 is not None:
            self.address_line2 = address_line2
        self.city = city
        self.state = state
        self.postal_code = postal_code
        if country is not None:
            self.country = country
        self.country_code = country_code
        self.email_address = email_address
        self.phone_number = phone_number
        self.payee_entity_type = payee_entity_type

    @property
    def payee_first_name(self):
        """Gets the payee_first_name of this PayeeContactInformation.  # noqa: E501

        First name of the payee. There is a 50 character limit.  # noqa: E501

        :return: The payee_first_name of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._payee_first_name

    @payee_first_name.setter
    def payee_first_name(self, payee_first_name):
        """Sets the payee_first_name of this PayeeContactInformation.

        First name of the payee. There is a 50 character limit.  # noqa: E501

        :param payee_first_name: The payee_first_name of this PayeeContactInformation.  # noqa: E501
        :type: str
        """
        if payee_first_name is None:
            raise ValueError("Invalid value for `payee_first_name`, must not be `None`")  # noqa: E501

        self._payee_first_name = payee_first_name

    @property
    def payee_middle_name(self):
        """Gets the payee_middle_name of this PayeeContactInformation.  # noqa: E501

        Middle name of the payee. There is a 50 character limit.  # noqa: E501

        :return: The payee_middle_name of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._payee_middle_name

    @payee_middle_name.setter
    def payee_middle_name(self, payee_middle_name):
        """Sets the payee_middle_name of this PayeeContactInformation.

        Middle name of the payee. There is a 50 character limit.  # noqa: E501

        :param payee_middle_name: The payee_middle_name of this PayeeContactInformation.  # noqa: E501
        :type: str
        """

        self._payee_middle_name = payee_middle_name

    @property
    def payee_last_name(self):
        """Gets the payee_last_name of this PayeeContactInformation.  # noqa: E501

        Last name of the payee. There is a 50 character limit.  # noqa: E501

        :return: The payee_last_name of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._payee_last_name

    @payee_last_name.setter
    def payee_last_name(self, payee_last_name):
        """Sets the payee_last_name of this PayeeContactInformation.

        Last name of the payee. There is a 50 character limit.  # noqa: E501

        :param payee_last_name: The payee_last_name of this PayeeContactInformation.  # noqa: E501
        :type: str
        """
        if payee_last_name is None:
            raise ValueError("Invalid value for `payee_last_name`, must not be `None`")  # noqa: E501

        self._payee_last_name = payee_last_name

    @property
    def address_line1(self):
        """Gets the address_line1 of this PayeeContactInformation.  # noqa: E501

        Address Line 1 of the public address.  # noqa: E501

        :return: The address_line1 of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._address_line1

    @address_line1.setter
    def address_line1(self, address_line1):
        """Sets the address_line1 of this PayeeContactInformation.

        Address Line 1 of the public address.  # noqa: E501

        :param address_line1: The address_line1 of this PayeeContactInformation.  # noqa: E501
        :type: str
        """
        if address_line1 is None:
            raise ValueError("Invalid value for `address_line1`, must not be `None`")  # noqa: E501

        self._address_line1 = address_line1

    @property
    def address_line2(self):
        """Gets the address_line2 of this PayeeContactInformation.  # noqa: E501

        Address Line 2 of the public address.  # noqa: E501

        :return: The address_line2 of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._address_line2

    @address_line2.setter
    def address_line2(self, address_line2):
        """Sets the address_line2 of this PayeeContactInformation.

        Address Line 2 of the public address.  # noqa: E501

        :param address_line2: The address_line2 of this PayeeContactInformation.  # noqa: E501
        :type: str
        """

        self._address_line2 = address_line2

    @property
    def city(self):
        """Gets the city of this PayeeContactInformation.  # noqa: E501

        City name of the public address.  # noqa: E501

        :return: The city of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this PayeeContactInformation.

        City name of the public address.  # noqa: E501

        :param city: The city of this PayeeContactInformation.  # noqa: E501
        :type: str
        """
        if city is None:
            raise ValueError("Invalid value for `city`, must not be `None`")  # noqa: E501

        self._city = city

    @property
    def state(self):
        """Gets the state of this PayeeContactInformation.  # noqa: E501

        State name of the public address. This is the state or region for China-based addresses.  # noqa: E501

        :return: The state of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this PayeeContactInformation.

        State name of the public address. This is the state or region for China-based addresses.  # noqa: E501

        :param state: The state of this PayeeContactInformation.  # noqa: E501
        :type: str
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def postal_code(self):
        """Gets the postal_code of this PayeeContactInformation.  # noqa: E501

        Postal code of the public address.  # noqa: E501

        :return: The postal_code of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this PayeeContactInformation.

        Postal code of the public address.  # noqa: E501

        :param postal_code: The postal_code of this PayeeContactInformation.  # noqa: E501
        :type: str
        """
        if postal_code is None:
            raise ValueError("Invalid value for `postal_code`, must not be `None`")  # noqa: E501

        self._postal_code = postal_code

    @property
    def country(self):
        """Gets the country of this PayeeContactInformation.  # noqa: E501

        Country name of the public address.  # noqa: E501

        :return: The country of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this PayeeContactInformation.

        Country name of the public address.  # noqa: E501

        :param country: The country of this PayeeContactInformation.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def country_code(self):
        """Gets the country_code of this PayeeContactInformation.  # noqa: E501

        The two digit country code, in ISO 3166 format.  # noqa: E501

        :return: The country_code of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this PayeeContactInformation.

        The two digit country code, in ISO 3166 format.  # noqa: E501

        :param country_code: The country_code of this PayeeContactInformation.  # noqa: E501
        :type: str
        """
        if country_code is None:
            raise ValueError("Invalid value for `country_code`, must not be `None`")  # noqa: E501

        self._country_code = country_code

    @property
    def email_address(self):
        """Gets the email_address of this PayeeContactInformation.  # noqa: E501

        Email address of the payee.  # noqa: E501

        :return: The email_address of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._email_address

    @email_address.setter
    def email_address(self, email_address):
        """Sets the email_address of this PayeeContactInformation.

        Email address of the payee.  # noqa: E501

        :param email_address: The email_address of this PayeeContactInformation.  # noqa: E501
        :type: str
        """
        if email_address is None:
            raise ValueError("Invalid value for `email_address`, must not be `None`")  # noqa: E501

        self._email_address = email_address

    @property
    def phone_number(self):
        """Gets the phone_number of this PayeeContactInformation.  # noqa: E501

        Valid phone number of the payee.  # noqa: E501

        :return: The phone_number of this PayeeContactInformation.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this PayeeContactInformation.

        Valid phone number of the payee.  # noqa: E501

        :param phone_number: The phone_number of this PayeeContactInformation.  # noqa: E501
        :type: str
        """
        if phone_number is None:
            raise ValueError("Invalid value for `phone_number`, must not be `None`")  # noqa: E501

        self._phone_number = phone_number

    @property
    def payee_entity_type(self):
        """Gets the payee_entity_type of this PayeeContactInformation.  # noqa: E501

        Type of entity of the payee.  # noqa: E501

        :return: The payee_entity_type of this PayeeContactInformation.  # noqa: E501
        :rtype: PayeeEntityType
        """
        return self._payee_entity_type

    @payee_entity_type.setter
    def payee_entity_type(self, payee_entity_type):
        """Sets the payee_entity_type of this PayeeContactInformation.

        Type of entity of the payee.  # noqa: E501

        :param payee_entity_type: The payee_entity_type of this PayeeContactInformation.  # noqa: E501
        :type: PayeeEntityType
        """
        if payee_entity_type is None:
            raise ValueError("Invalid value for `payee_entity_type`, must not be `None`")  # noqa: E501

        self._payee_entity_type = payee_entity_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PayeeContactInformation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PayeeContactInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
