# coding: utf-8

"""
    Selling Partner APIs for Fulfillment Outbound

    The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.  # noqa: E501

    OpenAPI spec version: 2020-07-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EventCode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    _101 = "EVENT_101"
    _102 = "EVENT_102"
    _201 = "EVENT_201"
    _202 = "EVENT_202"
    _203 = "EVENT_203"
    _204 = "EVENT_204"
    _205 = "EVENT_205"
    _206 = "EVENT_206"
    _301 = "EVENT_301"
    _302 = "EVENT_302"
    _304 = "EVENT_304"
    _306 = "EVENT_306"
    _307 = "EVENT_307"
    _308 = "EVENT_308"
    _309 = "EVENT_309"
    _401 = "EVENT_401"
    _402 = "EVENT_402"
    _403 = "EVENT_403"
    _404 = "EVENT_404"
    _405 = "EVENT_405"
    _406 = "EVENT_406"
    _407 = "EVENT_407"
    _408 = "EVENT_408"
    _409 = "EVENT_409"
    _411 = "EVENT_411"
    _412 = "EVENT_412"
    _413 = "EVENT_413"
    _414 = "EVENT_414"
    _415 = "EVENT_415"
    _416 = "EVENT_416"
    _417 = "EVENT_417"
    _418 = "EVENT_418"
    _419 = "EVENT_419"
    _801 = "EVENT_801"
    _804 = "EVENT_804"

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """EventCode - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventCode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventCode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
