# coding: utf-8

"""
    The Selling Partner API for FBA inbound operations.

    The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.  # noqa: E501

    OpenAPI spec version: 2024-03-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.item_input import ItemInput  # noqa: E501
from swagger_client.rest import ApiException


class TestItemInput(unittest.TestCase):
    """ItemInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemInput(self):
        """Test ItemInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.item_input.ItemInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
