# coding: utf-8

"""
    The Selling Partner API for Orders

    The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.  # noqa: E501

    OpenAPI spec version: 2026-01-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.associated_order_item import AssociatedOrderItem  # noqa: E501
from swagger_client.rest import ApiException


class TestAssociatedOrderItem(unittest.TestCase):
    """AssociatedOrderItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssociatedOrderItem(self):
        """Test AssociatedOrderItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.associated_order_item.AssociatedOrderItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
