# coding: utf-8

"""
    The Selling Partner API for Invoices.

    Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.  # noqa: E501

    OpenAPI spec version: 2024-06-19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InvoiceError(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'error_code': 'str'
    }

    attribute_map = {
        'description': 'description',
        'error_code': 'errorCode'
    }

    def __init__(self, description=None, error_code=None):  # noqa: E501
        """InvoiceError - a model defined in Swagger"""  # noqa: E501

        self._description = None
        self._error_code = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if error_code is not None:
            self.error_code = error_code

    @property
    def description(self):
        """Gets the description of this InvoiceError.  # noqa: E501

        A text description of the error.  # noqa: E501

        :return: The description of this InvoiceError.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InvoiceError.

        A text description of the error.  # noqa: E501

        :param description: The description of this InvoiceError.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def error_code(self):
        """Gets the error_code of this InvoiceError.  # noqa: E501

        The code of the error.  # noqa: E501

        :return: The error_code of this InvoiceError.  # noqa: E501
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this InvoiceError.

        The code of the error.  # noqa: E501

        :param error_code: The error_code of this InvoiceError.  # noqa: E501
        :type: str
        """

        self._error_code = error_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InvoiceError, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvoiceError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
