# coding: utf-8

"""
    Selling Partner API for Direct Fulfillment Payments

    The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tax_registration_detail import TaxRegistrationDetail  # noqa: E501
from swagger_client.rest import ApiException


class TestTaxRegistrationDetail(unittest.TestCase):
    """TaxRegistrationDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaxRegistrationDetail(self):
        """Test TaxRegistrationDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tax_registration_detail.TaxRegistrationDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
