# coding: utf-8

"""
    Selling Partner API for Pricing

    The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).  # noqa: E501

    OpenAPI spec version: 2022-05-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.competitive_summary_response_body import CompetitiveSummaryResponseBody  # noqa: E501
from swagger_client.rest import ApiException


class TestCompetitiveSummaryResponseBody(unittest.TestCase):
    """CompetitiveSummaryResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompetitiveSummaryResponseBody(self):
        """Test CompetitiveSummaryResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.competitive_summary_response_body.CompetitiveSummaryResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
