# coding: utf-8

"""
    Selling Partner API for Merchant Fulfillment

    With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ExcludedBenefit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'benefit': 'str',
        'reason_codes': 'ExcludedBenefitReasonCodes'
    }

    attribute_map = {
        'benefit': 'Benefit',
        'reason_codes': 'ReasonCodes'
    }

    def __init__(self, benefit=None, reason_codes=None):  # noqa: E501
        """ExcludedBenefit - a model defined in Swagger"""  # noqa: E501

        self._benefit = None
        self._reason_codes = None
        self.discriminator = None

        if benefit is not None:
            self.benefit = benefit
        if reason_codes is not None:
            self.reason_codes = reason_codes

    @property
    def benefit(self):
        """Gets the benefit of this ExcludedBenefit.  # noqa: E501

        A benefit that is being excluded from a shipment.  # noqa: E501

        :return: The benefit of this ExcludedBenefit.  # noqa: E501
        :rtype: str
        """
        return self._benefit

    @benefit.setter
    def benefit(self, benefit):
        """Sets the benefit of this ExcludedBenefit.

        A benefit that is being excluded from a shipment.  # noqa: E501

        :param benefit: The benefit of this ExcludedBenefit.  # noqa: E501
        :type: str
        """

        self._benefit = benefit

    @property
    def reason_codes(self):
        """Gets the reason_codes of this ExcludedBenefit.  # noqa: E501


        :return: The reason_codes of this ExcludedBenefit.  # noqa: E501
        :rtype: ExcludedBenefitReasonCodes
        """
        return self._reason_codes

    @reason_codes.setter
    def reason_codes(self, reason_codes):
        """Sets the reason_codes of this ExcludedBenefit.


        :param reason_codes: The reason_codes of this ExcludedBenefit.  # noqa: E501
        :type: ExcludedBenefitReasonCodes
        """

        self._reason_codes = reason_codes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExcludedBenefit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExcludedBenefit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
