# coding: utf-8

"""
    Selling Partner API for Direct Fulfillment Inventory Updates

    The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.submit_inventory_update_response import SubmitInventoryUpdateResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestSubmitInventoryUpdateResponse(unittest.TestCase):
    """SubmitInventoryUpdateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmitInventoryUpdateResponse(self):
        """Test SubmitInventoryUpdateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.submit_inventory_update_response.SubmitInventoryUpdateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
