# coding: utf-8

# flake8: noqa
"""
    Selling Partner API for Tokens 

    The Selling Partner API for Tokens provides a secure way to access a customer's PII (Personally Identifiable Information). You can call the Tokens API to get a Restricted Data Token (RDT) for one or more restricted resources that you specify. The RDT authorizes subsequent calls to restricted operations that correspond to the restricted resources that you specified.  For more information, see the [Tokens API Use Case Guide](doc:tokens-api-use-case-guide).  # noqa: E501

    OpenAPI spec version: 2021-03-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.create_restricted_data_token_request import CreateRestrictedDataTokenRequest
from swagger_client.models.create_restricted_data_token_response import CreateRestrictedDataTokenResponse
from swagger_client.models.error import Error
from swagger_client.models.error_list import ErrorList
from swagger_client.models.restricted_resource import RestrictedResource
