# coding: utf-8

"""
    The Selling Partner API for Invoices.

    Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.  # noqa: E501

    OpenAPI spec version: 2024-06-19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.invoices_api import InvoicesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInvoicesApi(unittest.TestCase):
    """InvoicesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.invoices_api.InvoicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_government_invoice(self):
        """Test case for create_government_invoice

        """
        pass

    def test_create_invoices_export(self):
        """Test case for create_invoices_export

        """
        pass

    def test_get_government_invoice_document(self):
        """Test case for get_government_invoice_document

        """
        pass

    def test_get_government_invoice_status(self):
        """Test case for get_government_invoice_status

        """
        pass

    def test_get_invoice(self):
        """Test case for get_invoice

        """
        pass

    def test_get_invoices(self):
        """Test case for get_invoices

        """
        pass

    def test_get_invoices_attributes(self):
        """Test case for get_invoices_attributes

        """
        pass

    def test_get_invoices_document(self):
        """Test case for get_invoices_document

        """
        pass

    def test_get_invoices_export(self):
        """Test case for get_invoices_export

        """
        pass

    def test_get_invoices_exports(self):
        """Test case for get_invoices_exports

        """
        pass


if __name__ == '__main__':
    unittest.main()