# coding: utf-8

"""
    The Selling Partner API for Invoices.

    Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.  # noqa: E501

    OpenAPI spec version: 2024-06-19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.government_invoice_status_response import GovernmentInvoiceStatusResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGovernmentInvoiceStatusResponse(unittest.TestCase):
    """GovernmentInvoiceStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGovernmentInvoiceStatusResponse(self):
        """Test GovernmentInvoiceStatusResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.government_invoice_status_response.GovernmentInvoiceStatusResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
