# coding: utf-8

"""
    The Selling Partner API for Finances

    The Selling Partner API for Finances provides financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.  # noqa: E501

    OpenAPI spec version: 2024-06-19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.payments_context import PaymentsContext  # noqa: E501
from swagger_client.rest import ApiException


class TestPaymentsContext(unittest.TestCase):
    """PaymentsContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentsContext(self):
        """Test PaymentsContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.payments_context.PaymentsContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
