# coding: utf-8

# flake8: noqa

"""
    Selling Partner API for Messaging

    With the Messaging API you can build applications that send messages to buyers. You can get a list of message types that are available for an order that you specify, then call an operation that sends a message to the buyer for that order. The Messaging API returns responses that are formed according to the <a href=https://tools.ietf.org/html/draft-kelly-json-hal-08>JSON Hypertext Application Language</a> (HAL) standard.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.messaging_api import MessagingApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.attachment import Attachment
from swagger_client.models.create_confirm_customization_details_request import CreateConfirmCustomizationDetailsRequest
from swagger_client.models.create_confirm_customization_details_response import CreateConfirmCustomizationDetailsResponse
from swagger_client.models.create_confirm_delivery_details_request import CreateConfirmDeliveryDetailsRequest
from swagger_client.models.create_confirm_delivery_details_response import CreateConfirmDeliveryDetailsResponse
from swagger_client.models.create_confirm_order_details_request import CreateConfirmOrderDetailsRequest
from swagger_client.models.create_confirm_order_details_response import CreateConfirmOrderDetailsResponse
from swagger_client.models.create_confirm_service_details_request import CreateConfirmServiceDetailsRequest
from swagger_client.models.create_confirm_service_details_response import CreateConfirmServiceDetailsResponse
from swagger_client.models.create_digital_access_key_request import CreateDigitalAccessKeyRequest
from swagger_client.models.create_digital_access_key_response import CreateDigitalAccessKeyResponse
from swagger_client.models.create_legal_disclosure_request import CreateLegalDisclosureRequest
from swagger_client.models.create_legal_disclosure_response import CreateLegalDisclosureResponse
from swagger_client.models.create_unexpected_problem_request import CreateUnexpectedProblemRequest
from swagger_client.models.create_unexpected_problem_response import CreateUnexpectedProblemResponse
from swagger_client.models.create_warranty_request import CreateWarrantyRequest
from swagger_client.models.create_warranty_response import CreateWarrantyResponse
from swagger_client.models.error import Error
from swagger_client.models.error_list import ErrorList
from swagger_client.models.get_attributes_response import GetAttributesResponse
from swagger_client.models.get_attributes_response_buyer import GetAttributesResponseBuyer
from swagger_client.models.get_messaging_action_response import GetMessagingActionResponse
from swagger_client.models.get_messaging_action_response_embedded import GetMessagingActionResponseEmbedded
from swagger_client.models.get_messaging_action_response_links import GetMessagingActionResponseLinks
from swagger_client.models.get_messaging_actions_for_order_response import GetMessagingActionsForOrderResponse
from swagger_client.models.get_messaging_actions_for_order_response_embedded import GetMessagingActionsForOrderResponseEmbedded
from swagger_client.models.get_messaging_actions_for_order_response_links import GetMessagingActionsForOrderResponseLinks
from swagger_client.models.get_schema_response import GetSchemaResponse
from swagger_client.models.get_schema_response_links import GetSchemaResponseLinks
from swagger_client.models.invoice_request import InvoiceRequest
from swagger_client.models.invoice_response import InvoiceResponse
from swagger_client.models.link_object import LinkObject
from swagger_client.models.messaging_action import MessagingAction
from swagger_client.models.schema import Schema
