# coding: utf-8

"""
    Selling Partner API for Retail Procurement Payments

    The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.net_cost_unit_of_measure import NetCostUnitOfMeasure  # noqa: E501
from swagger_client.rest import ApiException


class TestNetCostUnitOfMeasure(unittest.TestCase):
    """NetCostUnitOfMeasure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetCostUnitOfMeasure(self):
        """Test NetCostUnitOfMeasure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.net_cost_unit_of_measure.NetCostUnitOfMeasure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
