# coding: utf-8

"""
    Selling Partner API for Retail Procurement Payments

    The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.allowance_details import AllowanceDetails  # noqa: E501
from swagger_client.rest import ApiException


class TestAllowanceDetails(unittest.TestCase):
    """AllowanceDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllowanceDetails(self):
        """Test AllowanceDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.allowance_details.AllowanceDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
