# coding: utf-8

"""
    Selling Partner API for Retail Procurement Transaction Status

    The Selling Partner API for Retail Procurement Transaction Status provides programmatic access to status information on specific asynchronous POST transactions for vendors.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.vendor_transaction_api import VendorTransactionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVendorTransactionApi(unittest.TestCase):
    """VendorTransactionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.vendor_transaction_api.VendorTransactionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_transaction(self):
        """Test case for get_transaction

        """
        pass


if __name__ == '__main__':
    unittest.main()