# coding: utf-8

"""
    Selling Partner API for Retail Procurement Transaction Status

    The Selling Partner API for Retail Procurement Transaction Status provides programmatic access to status information on specific asynchronous POST transactions for vendors.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_transaction_response import GetTransactionResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetTransactionResponse(unittest.TestCase):
    """GetTransactionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTransactionResponse(self):
        """Test GetTransactionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_transaction_response.GetTransactionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
