# coding: utf-8

"""
    Selling Partner API for Retail Procurement Shipments

    The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.submit_shipments import SubmitShipments  # noqa: E501
from swagger_client.rest import ApiException


class TestSubmitShipments(unittest.TestCase):
    """SubmitShipments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmitShipments(self):
        """Test SubmitShipments"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.submit_shipments.SubmitShipments()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
