# coding: utf-8

"""
    Selling Partner API for Retail Procurement Shipments

    The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pallet import Pallet  # noqa: E501
from swagger_client.rest import ApiException


class TestPallet(unittest.TestCase):
    """Pallet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPallet(self):
        """Test Pallet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pallet.Pallet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
