# coding: utf-8

# flake8: noqa
"""
    Selling Partner API for Product Fees

    The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.error import Error
from swagger_client.models.error_list import ErrorList
from swagger_client.models.fee_detail import FeeDetail
from swagger_client.models.fee_detail_list import FeeDetailList
from swagger_client.models.fees_estimate import FeesEstimate
from swagger_client.models.fees_estimate_by_id_request import FeesEstimateByIdRequest
from swagger_client.models.fees_estimate_error import FeesEstimateError
from swagger_client.models.fees_estimate_error_detail import FeesEstimateErrorDetail
from swagger_client.models.fees_estimate_identifier import FeesEstimateIdentifier
from swagger_client.models.fees_estimate_request import FeesEstimateRequest
from swagger_client.models.fees_estimate_result import FeesEstimateResult
from swagger_client.models.get_my_fees_estimate_request import GetMyFeesEstimateRequest
from swagger_client.models.get_my_fees_estimate_response import GetMyFeesEstimateResponse
from swagger_client.models.get_my_fees_estimate_result import GetMyFeesEstimateResult
from swagger_client.models.get_my_fees_estimates_error_list import GetMyFeesEstimatesErrorList
from swagger_client.models.get_my_fees_estimates_request import GetMyFeesEstimatesRequest
from swagger_client.models.get_my_fees_estimates_response import GetMyFeesEstimatesResponse
from swagger_client.models.id_type import IdType
from swagger_client.models.included_fee_detail import IncludedFeeDetail
from swagger_client.models.included_fee_detail_list import IncludedFeeDetailList
from swagger_client.models.money_type import MoneyType
from swagger_client.models.optional_fulfillment_program import OptionalFulfillmentProgram
from swagger_client.models.points import Points
from swagger_client.models.price_to_estimate_fees import PriceToEstimateFees
