# coding: utf-8

"""
    The Selling Partner API for Amazon Seller Wallet Open Banking API

    The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.  # noqa: E501

    OpenAPI spec version: 2024-03-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transactions_api import TransactionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transactions_api.TransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_transaction(self):
        """Test case for create_transaction

        Create a transaction request from Amazon Seller Wallet account to another customer-provided account  # noqa: E501
        """
        pass

    def test_get_transaction(self):
        """Test case for get_transaction

        Find particular Amazon Seller Wallet account transaction by Amazon transaction identifier  # noqa: E501
        """
        pass

    def test_list_account_transactions(self):
        """Test case for list_account_transactions

        The API will return all the transactions for a given Amazon Seller Wallet account sorted by the transaction request date  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()