# coding: utf-8

"""
    The Selling Partner API for Amazon Seller Wallet Open Banking API

    The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.  # noqa: E501

    OpenAPI spec version: 2024-03-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transfer_preview_api import TransferPreviewApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransferPreviewApi(unittest.TestCase):
    """TransferPreviewApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transfer_preview_api.TransferPreviewApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_transfer_preview(self):
        """Test case for get_transfer_preview

        Fetch potential fees that could be applied on a transaction on the basis of the source and destination country currency code  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()