# coding: utf-8

"""
    Selling Partner API for Services

    With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.set_appointment_response import SetAppointmentResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestSetAppointmentResponse(unittest.TestCase):
    """SetAppointmentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetAppointmentResponse(self):
        """Test SetAppointmentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.set_appointment_response.SetAppointmentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
