# coding: utf-8

"""
    Selling Partner API for Services

    With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_schedule_response import UpdateScheduleResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateScheduleResponse(unittest.TestCase):
    """UpdateScheduleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateScheduleResponse(self):
        """Test UpdateScheduleResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_schedule_response.UpdateScheduleResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
