# coding: utf-8

"""
    Selling Partner API for Services

    With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.service_api import ServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.service_api.ServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_appointment_for_service_job_by_service_job_id(self):
        """Test case for add_appointment_for_service_job_by_service_job_id

        """
        pass

    def test_assign_appointment_resources(self):
        """Test case for assign_appointment_resources

        """
        pass

    def test_cancel_reservation(self):
        """Test case for cancel_reservation

        """
        pass

    def test_cancel_service_job_by_service_job_id(self):
        """Test case for cancel_service_job_by_service_job_id

        """
        pass

    def test_complete_service_job_by_service_job_id(self):
        """Test case for complete_service_job_by_service_job_id

        """
        pass

    def test_create_reservation(self):
        """Test case for create_reservation

        """
        pass

    def test_create_service_document_upload_destination(self):
        """Test case for create_service_document_upload_destination

        """
        pass

    def test_get_appointment_slots(self):
        """Test case for get_appointment_slots

        """
        pass

    def test_get_appointmment_slots_by_job_id(self):
        """Test case for get_appointmment_slots_by_job_id

        """
        pass

    def test_get_fixed_slot_capacity(self):
        """Test case for get_fixed_slot_capacity

        """
        pass

    def test_get_range_slot_capacity(self):
        """Test case for get_range_slot_capacity

        """
        pass

    def test_get_service_job_by_service_job_id(self):
        """Test case for get_service_job_by_service_job_id

        """
        pass

    def test_get_service_jobs(self):
        """Test case for get_service_jobs

        """
        pass

    def test_reschedule_appointment_for_service_job_by_service_job_id(self):
        """Test case for reschedule_appointment_for_service_job_by_service_job_id

        """
        pass

    def test_set_appointment_fulfillment_data(self):
        """Test case for set_appointment_fulfillment_data

        """
        pass

    def test_update_reservation(self):
        """Test case for update_reservation

        """
        pass

    def test_update_schedule(self):
        """Test case for update_schedule

        """
        pass


if __name__ == '__main__':
    unittest.main()