# coding: utf-8

"""
    Selling Partner API for Services

    With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.complete_service_job_by_service_job_id_response import CompleteServiceJobByServiceJobIdResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCompleteServiceJobByServiceJobIdResponse(unittest.TestCase):
    """CompleteServiceJobByServiceJobIdResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompleteServiceJobByServiceJobIdResponse(self):
        """Test CompleteServiceJobByServiceJobIdResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.complete_service_job_by_service_job_id_response.CompleteServiceJobByServiceJobIdResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
