# coding: utf-8

"""
    Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data

    The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.  # noqa: E501

    OpenAPI spec version: 2021-10-28
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.vendor_df_sandboxtransactionstatus_api import VendorDFSandboxtransactionstatusApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVendorDFSandboxtransactionstatusApi(unittest.TestCase):
    """VendorDFSandboxtransactionstatusApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.vendor_df_sandboxtransactionstatus_api.VendorDFSandboxtransactionstatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_order_scenarios(self):
        """Test case for get_order_scenarios

        """
        pass


if __name__ == '__main__':
    unittest.main()