# coding: utf-8

# flake8: noqa

"""
    Selling Partner API for Retail Procurement Shipments

    The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.vendor_shipping_api import VendorShippingApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.address import Address
from swagger_client.models.carrier_details import CarrierDetails
from swagger_client.models.carton import Carton
from swagger_client.models.carton_reference_details import CartonReferenceDetails
from swagger_client.models.collect_freight_pickup_details import CollectFreightPickupDetails
from swagger_client.models.container_identification import ContainerIdentification
from swagger_client.models.container_item import ContainerItem
from swagger_client.models.container_sequence_numbers import ContainerSequenceNumbers
from swagger_client.models.containers import Containers
from swagger_client.models.decimal import Decimal
from swagger_client.models.dimensions import Dimensions
from swagger_client.models.duration import Duration
from swagger_client.models.error import Error
from swagger_client.models.error_list import ErrorList
from swagger_client.models.expiry import Expiry
from swagger_client.models.get_shipment_details_response import GetShipmentDetailsResponse
from swagger_client.models.get_shipment_labels import GetShipmentLabels
from swagger_client.models.import_details import ImportDetails
from swagger_client.models.inner_containers_details import InnerContainersDetails
from swagger_client.models.item import Item
from swagger_client.models.item_details import ItemDetails
from swagger_client.models.item_quantity import ItemQuantity
from swagger_client.models.label_data import LabelData
from swagger_client.models.location import Location
from swagger_client.models.money import Money
from swagger_client.models.package_item_details import PackageItemDetails
from swagger_client.models.packed_items import PackedItems
from swagger_client.models.pagination import Pagination
from swagger_client.models.pallet import Pallet
from swagger_client.models.party_identification import PartyIdentification
from swagger_client.models.purchase_order_items import PurchaseOrderItems
from swagger_client.models.purchase_orders import PurchaseOrders
from swagger_client.models.regulation_references import RegulationReferences
from swagger_client.models.route import Route
from swagger_client.models.shipment import Shipment
from swagger_client.models.shipment_confirmation import ShipmentConfirmation
from swagger_client.models.shipment_details import ShipmentDetails
from swagger_client.models.shipment_information import ShipmentInformation
from swagger_client.models.shipment_measurements import ShipmentMeasurements
from swagger_client.models.shipment_status_details import ShipmentStatusDetails
from swagger_client.models.stop import Stop
from swagger_client.models.submit_shipment_confirmations_request import SubmitShipmentConfirmationsRequest
from swagger_client.models.submit_shipment_confirmations_response import SubmitShipmentConfirmationsResponse
from swagger_client.models.submit_shipments import SubmitShipments
from swagger_client.models.tax_registration_details import TaxRegistrationDetails
from swagger_client.models.total_weight import TotalWeight
from swagger_client.models.transaction_reference import TransactionReference
from swagger_client.models.transport_label import TransportLabel
from swagger_client.models.transport_shipment_measurements import TransportShipmentMeasurements
from swagger_client.models.transportation_details import TransportationDetails
from swagger_client.models.transportation_details_for_shipment_confirmation import TransportationDetailsForShipmentConfirmation
from swagger_client.models.transportation_labels import TransportationLabels
from swagger_client.models.vendor_details import VendorDetails
from swagger_client.models.volume import Volume
from swagger_client.models.weight import Weight
