# coding: utf-8

"""
    Selling Partner API for Services

    With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Payment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'MoneyAmount',
        'instrument': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'instrument': 'instrument'
    }

    def __init__(self, amount=None, instrument=None):  # noqa: E501
        """Payment - a model defined in Swagger"""  # noqa: E501

        self._amount = None
        self._instrument = None
        self.discriminator = None

        if amount is not None:
            self.amount = amount
        if instrument is not None:
            self.instrument = instrument

    @property
    def amount(self):
        """Gets the amount of this Payment.  # noqa: E501

        The payment amount.  # noqa: E501

        :return: The amount of this Payment.  # noqa: E501
        :rtype: MoneyAmount
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Payment.

        The payment amount.  # noqa: E501

        :param amount: The amount of this Payment.  # noqa: E501
        :type: MoneyAmount
        """

        self._amount = amount

    @property
    def instrument(self):
        """Gets the instrument of this Payment.  # noqa: E501

        The payment instrument used for the transaction.  # noqa: E501

        :return: The instrument of this Payment.  # noqa: E501
        :rtype: str
        """
        return self._instrument

    @instrument.setter
    def instrument(self, instrument):
        """Sets the instrument of this Payment.

        The payment instrument used for the transaction.  # noqa: E501

        :param instrument: The instrument of this Payment.  # noqa: E501
        :type: str
        """

        self._instrument = instrument

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Payment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Payment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
