# coding: utf-8

"""
    Selling Partner API for Services

    With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UpdateReservationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_id': 'str',
        'reservation': 'Reservation'
    }

    attribute_map = {
        'resource_id': 'resourceId',
        'reservation': 'reservation'
    }

    def __init__(self, resource_id=None, reservation=None):  # noqa: E501
        """UpdateReservationRequest - a model defined in Swagger"""  # noqa: E501

        self._resource_id = None
        self._reservation = None
        self.discriminator = None

        self.resource_id = resource_id
        self.reservation = reservation

    @property
    def resource_id(self):
        """Gets the resource_id of this UpdateReservationRequest.  # noqa: E501

        Resource (store) identifier.  # noqa: E501

        :return: The resource_id of this UpdateReservationRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this UpdateReservationRequest.

        Resource (store) identifier.  # noqa: E501

        :param resource_id: The resource_id of this UpdateReservationRequest.  # noqa: E501
        :type: str
        """
        if resource_id is None:
            raise ValueError("Invalid value for `resource_id`, must not be `None`")  # noqa: E501

        self._resource_id = resource_id

    @property
    def reservation(self):
        """Gets the reservation of this UpdateReservationRequest.  # noqa: E501

        `Reservation` object to reduce the capacity of a resource.  # noqa: E501

        :return: The reservation of this UpdateReservationRequest.  # noqa: E501
        :rtype: Reservation
        """
        return self._reservation

    @reservation.setter
    def reservation(self, reservation):
        """Sets the reservation of this UpdateReservationRequest.

        `Reservation` object to reduce the capacity of a resource.  # noqa: E501

        :param reservation: The reservation of this UpdateReservationRequest.  # noqa: E501
        :type: Reservation
        """
        if reservation is None:
            raise ValueError("Invalid value for `reservation`, must not be `None`")  # noqa: E501

        self._reservation = reservation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateReservationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateReservationRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
