# coding: utf-8

"""
    Selling Partner API for Direct Fulfillment Shipping

    Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.  # noqa: E501

    OpenAPI spec version: 2021-12-28
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Dimensions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'length': 'Decimal',
        'width': 'Decimal',
        'height': 'Decimal',
        'unit_of_measure': 'str'
    }

    attribute_map = {
        'length': 'length',
        'width': 'width',
        'height': 'height',
        'unit_of_measure': 'unitOfMeasure'
    }

    def __init__(self, length=None, width=None, height=None, unit_of_measure=None):  # noqa: E501
        """Dimensions - a model defined in Swagger"""  # noqa: E501

        self._length = None
        self._width = None
        self._height = None
        self._unit_of_measure = None
        self.discriminator = None

        self.length = length
        self.width = width
        self.height = height
        self.unit_of_measure = unit_of_measure

    @property
    def length(self):
        """Gets the length of this Dimensions.  # noqa: E501

        The length of the container.  # noqa: E501

        :return: The length of this Dimensions.  # noqa: E501
        :rtype: Decimal
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this Dimensions.

        The length of the container.  # noqa: E501

        :param length: The length of this Dimensions.  # noqa: E501
        :type: Decimal
        """
        if length is None:
            raise ValueError("Invalid value for `length`, must not be `None`")  # noqa: E501

        self._length = length

    @property
    def width(self):
        """Gets the width of this Dimensions.  # noqa: E501

        The width of the container.  # noqa: E501

        :return: The width of this Dimensions.  # noqa: E501
        :rtype: Decimal
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this Dimensions.

        The width of the container.  # noqa: E501

        :param width: The width of this Dimensions.  # noqa: E501
        :type: Decimal
        """
        if width is None:
            raise ValueError("Invalid value for `width`, must not be `None`")  # noqa: E501

        self._width = width

    @property
    def height(self):
        """Gets the height of this Dimensions.  # noqa: E501

        The height of the container.  # noqa: E501

        :return: The height of this Dimensions.  # noqa: E501
        :rtype: Decimal
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this Dimensions.

        The height of the container.  # noqa: E501

        :param height: The height of this Dimensions.  # noqa: E501
        :type: Decimal
        """
        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")  # noqa: E501

        self._height = height

    @property
    def unit_of_measure(self):
        """Gets the unit_of_measure of this Dimensions.  # noqa: E501

        The unit of measure for dimensions.  # noqa: E501

        :return: The unit_of_measure of this Dimensions.  # noqa: E501
        :rtype: str
        """
        return self._unit_of_measure

    @unit_of_measure.setter
    def unit_of_measure(self, unit_of_measure):
        """Sets the unit_of_measure of this Dimensions.

        The unit of measure for dimensions.  # noqa: E501

        :param unit_of_measure: The unit_of_measure of this Dimensions.  # noqa: E501
        :type: str
        """
        if unit_of_measure is None:
            raise ValueError("Invalid value for `unit_of_measure`, must not be `None`")  # noqa: E501
        allowed_values = ["IN", "CM"]  # noqa: E501
        if unit_of_measure not in allowed_values:
            raise ValueError(
                "Invalid value for `unit_of_measure` ({0}), must be one of {1}"  # noqa: E501
                .format(unit_of_measure, allowed_values)
            )

        self._unit_of_measure = unit_of_measure

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Dimensions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Dimensions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
