# coding: utf-8

"""
    Selling Partner API for Merchant Fulfillment

    With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.carrier_will_pick_up_option import CarrierWillPickUpOption  # noqa: E501
from swagger_client.rest import ApiException


class TestCarrierWillPickUpOption(unittest.TestCase):
    """CarrierWillPickUpOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCarrierWillPickUpOption(self):
        """Test CarrierWillPickUpOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.carrier_will_pick_up_option.CarrierWillPickUpOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
