# coding: utf-8

"""
    Selling Partner API for Merchant Fulfillment

    With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_eligible_shipment_services_request import GetEligibleShipmentServicesRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestGetEligibleShipmentServicesRequest(unittest.TestCase):
    """GetEligibleShipmentServicesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEligibleShipmentServicesRequest(self):
        """Test GetEligibleShipmentServicesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_eligible_shipment_services_request.GetEligibleShipmentServicesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
