# coding: utf-8

"""
    Selling Partner API for Uploads

    The Uploads API lets you upload files that you can programmatically access using other Selling Partner APIs, such as the A+ Content API and the Messaging API.  # noqa: E501

    OpenAPI spec version: 2020-11-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_upload_destination_response import CreateUploadDestinationResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateUploadDestinationResponse(unittest.TestCase):
    """CreateUploadDestinationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUploadDestinationResponse(self):
        """Test CreateUploadDestinationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_upload_destination_response.CreateUploadDestinationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
