# coding: utf-8

"""
    Selling Partner API for A+ Content Management

    Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.  # noqa: E501

    OpenAPI spec version: 2020-11-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ContentMetadataRecord(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content_reference_key': 'ContentReferenceKey',
        'content_metadata': 'ContentMetadata'
    }

    attribute_map = {
        'content_reference_key': 'contentReferenceKey',
        'content_metadata': 'contentMetadata'
    }

    def __init__(self, content_reference_key=None, content_metadata=None):  # noqa: E501
        """ContentMetadataRecord - a model defined in Swagger"""  # noqa: E501

        self._content_reference_key = None
        self._content_metadata = None
        self.discriminator = None

        self.content_reference_key = content_reference_key
        self.content_metadata = content_metadata

    @property
    def content_reference_key(self):
        """Gets the content_reference_key of this ContentMetadataRecord.  # noqa: E501


        :return: The content_reference_key of this ContentMetadataRecord.  # noqa: E501
        :rtype: ContentReferenceKey
        """
        return self._content_reference_key

    @content_reference_key.setter
    def content_reference_key(self, content_reference_key):
        """Sets the content_reference_key of this ContentMetadataRecord.


        :param content_reference_key: The content_reference_key of this ContentMetadataRecord.  # noqa: E501
        :type: ContentReferenceKey
        """
        if content_reference_key is None:
            raise ValueError("Invalid value for `content_reference_key`, must not be `None`")  # noqa: E501

        self._content_reference_key = content_reference_key

    @property
    def content_metadata(self):
        """Gets the content_metadata of this ContentMetadataRecord.  # noqa: E501


        :return: The content_metadata of this ContentMetadataRecord.  # noqa: E501
        :rtype: ContentMetadata
        """
        return self._content_metadata

    @content_metadata.setter
    def content_metadata(self, content_metadata):
        """Sets the content_metadata of this ContentMetadataRecord.


        :param content_metadata: The content_metadata of this ContentMetadataRecord.  # noqa: E501
        :type: ContentMetadata
        """
        if content_metadata is None:
            raise ValueError("Invalid value for `content_metadata`, must not be `None`")  # noqa: E501

        self._content_metadata = content_metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContentMetadataRecord, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContentMetadataRecord):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
