# coding: utf-8

"""
    Selling Partner API for A+ Content Management

    Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.  # noqa: E501

    OpenAPI spec version: 2020-11-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SearchContentPublishRecordsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'warnings': 'MessageSet',
        'next_page_token': 'PageToken',
        'publish_record_list': 'PublishRecordList'
    }

    attribute_map = {
        'warnings': 'warnings',
        'next_page_token': 'nextPageToken',
        'publish_record_list': 'publishRecordList'
    }

    def __init__(self, warnings=None, next_page_token=None, publish_record_list=None):  # noqa: E501
        """SearchContentPublishRecordsResponse - a model defined in Swagger"""  # noqa: E501

        self._warnings = None
        self._next_page_token = None
        self._publish_record_list = None
        self.discriminator = None

        if warnings is not None:
            self.warnings = warnings
        if next_page_token is not None:
            self.next_page_token = next_page_token
        self.publish_record_list = publish_record_list

    @property
    def warnings(self):
        """Gets the warnings of this SearchContentPublishRecordsResponse.  # noqa: E501


        :return: The warnings of this SearchContentPublishRecordsResponse.  # noqa: E501
        :rtype: MessageSet
        """
        return self._warnings

    @warnings.setter
    def warnings(self, warnings):
        """Sets the warnings of this SearchContentPublishRecordsResponse.


        :param warnings: The warnings of this SearchContentPublishRecordsResponse.  # noqa: E501
        :type: MessageSet
        """

        self._warnings = warnings

    @property
    def next_page_token(self):
        """Gets the next_page_token of this SearchContentPublishRecordsResponse.  # noqa: E501


        :return: The next_page_token of this SearchContentPublishRecordsResponse.  # noqa: E501
        :rtype: PageToken
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token):
        """Sets the next_page_token of this SearchContentPublishRecordsResponse.


        :param next_page_token: The next_page_token of this SearchContentPublishRecordsResponse.  # noqa: E501
        :type: PageToken
        """

        self._next_page_token = next_page_token

    @property
    def publish_record_list(self):
        """Gets the publish_record_list of this SearchContentPublishRecordsResponse.  # noqa: E501


        :return: The publish_record_list of this SearchContentPublishRecordsResponse.  # noqa: E501
        :rtype: PublishRecordList
        """
        return self._publish_record_list

    @publish_record_list.setter
    def publish_record_list(self, publish_record_list):
        """Sets the publish_record_list of this SearchContentPublishRecordsResponse.


        :param publish_record_list: The publish_record_list of this SearchContentPublishRecordsResponse.  # noqa: E501
        :type: PublishRecordList
        """
        if publish_record_list is None:
            raise ValueError("Invalid value for `publish_record_list`, must not be `None`")  # noqa: E501

        self._publish_record_list = publish_record_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchContentPublishRecordsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchContentPublishRecordsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
