# coding: utf-8

"""
    Selling Partner API for Messaging

    With the Messaging API you can build applications that send messages to buyers. You can get a list of message types that are available for an order that you specify, then call an operation that sends a message to the buyer for that order. The Messaging API returns responses that are formed according to the <a href=https://tools.ietf.org/html/draft-kelly-json-hal-08>JSON Hypertext Application Language</a> (HAL) standard.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.link_object import LinkObject  # noqa: E501
from swagger_client.rest import ApiException


class TestLinkObject(unittest.TestCase):
    """LinkObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkObject(self):
        """Test LinkObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.link_object.LinkObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
