# coding: utf-8

"""
    Selling Partner API for Shipment Invoicing

    The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.payment_information_list import PaymentInformationList  # noqa: E501
from swagger_client.rest import ApiException


class TestPaymentInformationList(unittest.TestCase):
    """PaymentInformationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentInformationList(self):
        """Test PaymentInformationList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.payment_information_list.PaymentInformationList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
