# coding: utf-8

# flake8: noqa
"""
    The Selling Partner API for Sellers

    The [Selling Partner API for Sellers](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) (Sellers API) provides essential information about seller accounts, such as:  - The marketplaces a seller can list in - The default language and currency of a marketplace - Whether the seller has suspended listings  Refer to the [Sellers API reference](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) for details about this API's operations, data types, and schemas.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.account import Account
from swagger_client.models.address import Address
from swagger_client.models.business import Business
from swagger_client.models.error import Error
from swagger_client.models.error_list import ErrorList
from swagger_client.models.get_account_response import GetAccountResponse
from swagger_client.models.get_marketplace_participations_response import GetMarketplaceParticipationsResponse
from swagger_client.models.marketplace import Marketplace
from swagger_client.models.marketplace_participation import MarketplaceParticipation
from swagger_client.models.marketplace_participation_list import MarketplaceParticipationList
from swagger_client.models.participation import Participation
from swagger_client.models.primary_contact import PrimaryContact
