# coding: utf-8

"""
    The Selling Partner API for Amazon Warehousing and Distribution

    The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.   # noqa: E501

    OpenAPI spec version: 2024-05-09
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sku_quantity import SkuQuantity  # noqa: E501
from swagger_client.rest import ApiException


class TestSkuQuantity(unittest.TestCase):
    """SkuQuantity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSkuQuantity(self):
        """Test SkuQuantity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sku_quantity.SkuQuantity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
