# coding: utf-8

"""
    The Selling Partner API for Amazon Warehousing and Distribution

    The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.   # noqa: E501

    OpenAPI spec version: 2024-05-09
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tracking_details import TrackingDetails  # noqa: E501
from swagger_client.rest import ApiException


class TestTrackingDetails(unittest.TestCase):
    """TrackingDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackingDetails(self):
        """Test TrackingDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tracking_details.TrackingDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
