# coding: utf-8

"""
    Selling Partner API for Retail Procurement Orders

    The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ordered_quantity_details import OrderedQuantityDetails  # noqa: E501
from swagger_client.rest import ApiException


class TestOrderedQuantityDetails(unittest.TestCase):
    """OrderedQuantityDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderedQuantityDetails(self):
        """Test OrderedQuantityDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ordered_quantity_details.OrderedQuantityDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
