# coding: utf-8

"""
    Selling Partner API for Product Type Definitions

    The Selling Partner API for Product Type Definitions provides programmatic access to attribute and data requirements for product types in the Amazon catalog. Use this API to return the JSON Schema for a product type that you can then use with other Selling Partner APIs, such as the Selling Partner API for Listings Items, the Selling Partner API for Catalog Items, and the Selling Partner API for Feeds (for JSON-based listing feeds).  For more information, see the [Product Type Definitions API Use Case Guide](doc:product-type-api-use-case-guide).  # noqa: E501

    OpenAPI spec version: 2020-09-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.product_type import ProductType  # noqa: E501
from swagger_client.rest import ApiException


class TestProductType(unittest.TestCase):
    """ProductType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductType(self):
        """Test ProductType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.product_type.ProductType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
