# coding: utf-8

"""
    Selling Partner API for Product Type Definitions

    The Selling Partner API for Product Type Definitions provides programmatic access to attribute and data requirements for product types in the Amazon catalog. Use this API to return the JSON Schema for a product type that you can then use with other Selling Partner APIs, such as the Selling Partner API for Listings Items, the Selling Partner API for Catalog Items, and the Selling Partner API for Feeds (for JSON-based listing feeds).  For more information, see the [Product Type Definitions API Use Case Guide](doc:product-type-api-use-case-guide).  # noqa: E501

    OpenAPI spec version: 2020-09-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.definitions_api import DefinitionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefinitionsApi(unittest.TestCase):
    """DefinitionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.definitions_api.DefinitionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_definitions_product_type(self):
        """Test case for get_definitions_product_type

        """
        pass

    def test_search_definitions_product_types(self):
        """Test case for search_definitions_product_types

        """
        pass


if __name__ == '__main__':
    unittest.main()