# coding: utf-8

"""
    The Selling Partner API for Orders

    The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.  # noqa: E501

    OpenAPI spec version: 2026-01-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Buyer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'buyer_name': 'str',
        'buyer_email': 'str',
        'buyer_company_name': 'str',
        'buyer_purchase_order_number': 'str'
    }

    attribute_map = {
        'buyer_name': 'buyerName',
        'buyer_email': 'buyerEmail',
        'buyer_company_name': 'buyerCompanyName',
        'buyer_purchase_order_number': 'buyerPurchaseOrderNumber'
    }

    def __init__(self, buyer_name=None, buyer_email=None, buyer_company_name=None, buyer_purchase_order_number=None):  # noqa: E501
        """Buyer - a model defined in Swagger"""  # noqa: E501

        self._buyer_name = None
        self._buyer_email = None
        self._buyer_company_name = None
        self._buyer_purchase_order_number = None
        self.discriminator = None

        if buyer_name is not None:
            self.buyer_name = buyer_name
        if buyer_email is not None:
            self.buyer_email = buyer_email
        if buyer_company_name is not None:
            self.buyer_company_name = buyer_company_name
        if buyer_purchase_order_number is not None:
            self.buyer_purchase_order_number = buyer_purchase_order_number

    @property
    def buyer_name(self):
        """Gets the buyer_name of this Buyer.  # noqa: E501

        The full name of the customer who placed the order.  # noqa: E501

        :return: The buyer_name of this Buyer.  # noqa: E501
        :rtype: str
        """
        return self._buyer_name

    @buyer_name.setter
    def buyer_name(self, buyer_name):
        """Sets the buyer_name of this Buyer.

        The full name of the customer who placed the order.  # noqa: E501

        :param buyer_name: The buyer_name of this Buyer.  # noqa: E501
        :type: str
        """

        self._buyer_name = buyer_name

    @property
    def buyer_email(self):
        """Gets the buyer_email of this Buyer.  # noqa: E501

        The anonymized email address of the buyer. **Note:** Only available for merchant-fulfilled (FBM) orders.  # noqa: E501

        :return: The buyer_email of this Buyer.  # noqa: E501
        :rtype: str
        """
        return self._buyer_email

    @buyer_email.setter
    def buyer_email(self, buyer_email):
        """Sets the buyer_email of this Buyer.

        The anonymized email address of the buyer. **Note:** Only available for merchant-fulfilled (FBM) orders.  # noqa: E501

        :param buyer_email: The buyer_email of this Buyer.  # noqa: E501
        :type: str
        """

        self._buyer_email = buyer_email

    @property
    def buyer_company_name(self):
        """Gets the buyer_company_name of this Buyer.  # noqa: E501

        The name of the company or organization for a business order.  # noqa: E501

        :return: The buyer_company_name of this Buyer.  # noqa: E501
        :rtype: str
        """
        return self._buyer_company_name

    @buyer_company_name.setter
    def buyer_company_name(self, buyer_company_name):
        """Sets the buyer_company_name of this Buyer.

        The name of the company or organization for a business order.  # noqa: E501

        :param buyer_company_name: The buyer_company_name of this Buyer.  # noqa: E501
        :type: str
        """

        self._buyer_company_name = buyer_company_name

    @property
    def buyer_purchase_order_number(self):
        """Gets the buyer_purchase_order_number of this Buyer.  # noqa: E501

        The purchase order (PO) number entered by the buyer at checkout. Only returned for orders where the buyer entered a PO number at checkout.  # noqa: E501

        :return: The buyer_purchase_order_number of this Buyer.  # noqa: E501
        :rtype: str
        """
        return self._buyer_purchase_order_number

    @buyer_purchase_order_number.setter
    def buyer_purchase_order_number(self, buyer_purchase_order_number):
        """Sets the buyer_purchase_order_number of this Buyer.

        The purchase order (PO) number entered by the buyer at checkout. Only returned for orders where the buyer entered a PO number at checkout.  # noqa: E501

        :param buyer_purchase_order_number: The buyer_purchase_order_number of this Buyer.  # noqa: E501
        :type: str
        """

        self._buyer_purchase_order_number = buyer_purchase_order_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Buyer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Buyer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
