# coding: utf-8

"""
    The Selling Partner API for Orders

    The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.  # noqa: E501

    OpenAPI spec version: 2026-01-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CustomerAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'company_name': 'str',
        'address_line1': 'str',
        'address_line2': 'str',
        'address_line3': 'str',
        'city': 'str',
        'district_or_county': 'str',
        'state_or_region': 'str',
        'municipality': 'str',
        'postal_code': 'str',
        'country_code': 'str',
        'phone': 'str',
        'extended_fields': 'AddressExtendedFields',
        'address_type': 'str'
    }

    attribute_map = {
        'name': 'name',
        'company_name': 'companyName',
        'address_line1': 'addressLine1',
        'address_line2': 'addressLine2',
        'address_line3': 'addressLine3',
        'city': 'city',
        'district_or_county': 'districtOrCounty',
        'state_or_region': 'stateOrRegion',
        'municipality': 'municipality',
        'postal_code': 'postalCode',
        'country_code': 'countryCode',
        'phone': 'phone',
        'extended_fields': 'extendedFields',
        'address_type': 'addressType'
    }

    def __init__(self, name=None, company_name=None, address_line1=None, address_line2=None, address_line3=None, city=None, district_or_county=None, state_or_region=None, municipality=None, postal_code=None, country_code=None, phone=None, extended_fields=None, address_type=None):  # noqa: E501
        """CustomerAddress - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._company_name = None
        self._address_line1 = None
        self._address_line2 = None
        self._address_line3 = None
        self._city = None
        self._district_or_county = None
        self._state_or_region = None
        self._municipality = None
        self._postal_code = None
        self._country_code = None
        self._phone = None
        self._extended_fields = None
        self._address_type = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if company_name is not None:
            self.company_name = company_name
        if address_line1 is not None:
            self.address_line1 = address_line1
        if address_line2 is not None:
            self.address_line2 = address_line2
        if address_line3 is not None:
            self.address_line3 = address_line3
        if city is not None:
            self.city = city
        if district_or_county is not None:
            self.district_or_county = district_or_county
        if state_or_region is not None:
            self.state_or_region = state_or_region
        if municipality is not None:
            self.municipality = municipality
        if postal_code is not None:
            self.postal_code = postal_code
        if country_code is not None:
            self.country_code = country_code
        if phone is not None:
            self.phone = phone
        if extended_fields is not None:
            self.extended_fields = extended_fields
        if address_type is not None:
            self.address_type = address_type

    @property
    def name(self):
        """Gets the name of this CustomerAddress.  # noqa: E501

        The full name of the person who will receive the delivery at this address.  # noqa: E501

        :return: The name of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CustomerAddress.

        The full name of the person who will receive the delivery at this address.  # noqa: E501

        :param name: The name of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def company_name(self):
        """Gets the company_name of this CustomerAddress.  # noqa: E501

        The name of the business or organization at this address.  # noqa: E501

        :return: The company_name of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this CustomerAddress.

        The name of the business or organization at this address.  # noqa: E501

        :param company_name: The company_name of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    @property
    def address_line1(self):
        """Gets the address_line1 of this CustomerAddress.  # noqa: E501

        The primary street address.  # noqa: E501

        :return: The address_line1 of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._address_line1

    @address_line1.setter
    def address_line1(self, address_line1):
        """Sets the address_line1 of this CustomerAddress.

        The primary street address.  # noqa: E501

        :param address_line1: The address_line1 of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._address_line1 = address_line1

    @property
    def address_line2(self):
        """Gets the address_line2 of this CustomerAddress.  # noqa: E501

        Additional address information.  # noqa: E501

        :return: The address_line2 of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._address_line2

    @address_line2.setter
    def address_line2(self, address_line2):
        """Sets the address_line2 of this CustomerAddress.

        Additional address information.  # noqa: E501

        :param address_line2: The address_line2 of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._address_line2 = address_line2

    @property
    def address_line3(self):
        """Gets the address_line3 of this CustomerAddress.  # noqa: E501

        Additional address information.  # noqa: E501

        :return: The address_line3 of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._address_line3

    @address_line3.setter
    def address_line3(self, address_line3):
        """Sets the address_line3 of this CustomerAddress.

        Additional address information.  # noqa: E501

        :param address_line3: The address_line3 of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._address_line3 = address_line3

    @property
    def city(self):
        """Gets the city of this CustomerAddress.  # noqa: E501

        The city of the address.  # noqa: E501

        :return: The city of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this CustomerAddress.

        The city of the address.  # noqa: E501

        :param city: The city of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def district_or_county(self):
        """Gets the district_or_county of this CustomerAddress.  # noqa: E501

        The district or county of the address.  # noqa: E501

        :return: The district_or_county of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._district_or_county

    @district_or_county.setter
    def district_or_county(self, district_or_county):
        """Sets the district_or_county of this CustomerAddress.

        The district or county of the address.  # noqa: E501

        :param district_or_county: The district_or_county of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._district_or_county = district_or_county

    @property
    def state_or_region(self):
        """Gets the state_or_region of this CustomerAddress.  # noqa: E501

        The state, province, or region of the address.  # noqa: E501

        :return: The state_or_region of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._state_or_region

    @state_or_region.setter
    def state_or_region(self, state_or_region):
        """Sets the state_or_region of this CustomerAddress.

        The state, province, or region of the address.  # noqa: E501

        :param state_or_region: The state_or_region of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._state_or_region = state_or_region

    @property
    def municipality(self):
        """Gets the municipality of this CustomerAddress.  # noqa: E501

        The municipality of the address.  # noqa: E501

        :return: The municipality of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._municipality

    @municipality.setter
    def municipality(self, municipality):
        """Sets the municipality of this CustomerAddress.

        The municipality of the address.  # noqa: E501

        :param municipality: The municipality of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._municipality = municipality

    @property
    def postal_code(self):
        """Gets the postal_code of this CustomerAddress.  # noqa: E501

        The postal code, ZIP code, or equivalent mailing code of the address.  # noqa: E501

        :return: The postal_code of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this CustomerAddress.

        The postal code, ZIP code, or equivalent mailing code of the address.  # noqa: E501

        :param postal_code: The postal_code of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._postal_code = postal_code

    @property
    def country_code(self):
        """Gets the country_code of this CustomerAddress.  # noqa: E501

        The two-letter country code identifying the country of the address, in ISO 3166-1 format.  # noqa: E501

        :return: The country_code of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this CustomerAddress.

        The two-letter country code identifying the country of the address, in ISO 3166-1 format.  # noqa: E501

        :param country_code: The country_code of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._country_code = country_code

    @property
    def phone(self):
        """Gets the phone of this CustomerAddress.  # noqa: E501

        The contact phone number for delivery coordination and customer communication.  **Note**: The buyer phone number will be suppressed in some cases, including but not limited to:  - All FBA (Fulfillment by Amazon) orders. - Shipped FBM (Fulfilled by the merchant) orders when current date is past the latest delivery date.  # noqa: E501

        :return: The phone of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this CustomerAddress.

        The contact phone number for delivery coordination and customer communication.  **Note**: The buyer phone number will be suppressed in some cases, including but not limited to:  - All FBA (Fulfillment by Amazon) orders. - Shipped FBM (Fulfilled by the merchant) orders when current date is past the latest delivery date.  # noqa: E501

        :param phone: The phone of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def extended_fields(self):
        """Gets the extended_fields of this CustomerAddress.  # noqa: E501

        Additional address components specific to certain countries that provide more detailed location information.  **Note**: Only available with Brazil shipping addresses.  # noqa: E501

        :return: The extended_fields of this CustomerAddress.  # noqa: E501
        :rtype: AddressExtendedFields
        """
        return self._extended_fields

    @extended_fields.setter
    def extended_fields(self, extended_fields):
        """Sets the extended_fields of this CustomerAddress.

        Additional address components specific to certain countries that provide more detailed location information.  **Note**: Only available with Brazil shipping addresses.  # noqa: E501

        :param extended_fields: The extended_fields of this CustomerAddress.  # noqa: E501
        :type: AddressExtendedFields
        """

        self._extended_fields = extended_fields

    @property
    def address_type(self):
        """Gets the address_type of this CustomerAddress.  # noqa: E501

        The type of location.  **Possible values**: `RESIDENTIAL`, `COMMERCIAL`, `PICKUP_POINT`  # noqa: E501

        :return: The address_type of this CustomerAddress.  # noqa: E501
        :rtype: str
        """
        return self._address_type

    @address_type.setter
    def address_type(self, address_type):
        """Sets the address_type of this CustomerAddress.

        The type of location.  **Possible values**: `RESIDENTIAL`, `COMMERCIAL`, `PICKUP_POINT`  # noqa: E501

        :param address_type: The address_type of this CustomerAddress.  # noqa: E501
        :type: str
        """

        self._address_type = address_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomerAddress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomerAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
