# coding: utf-8

"""
    The Selling Partner API for Orders

    The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.  # noqa: E501

    OpenAPI spec version: 2026-01-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ItemProceedsBreakdown(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'subtotal': 'Money',
        'detailed_breakdowns': 'list[ItemProceedsDetailedBreakdown]'
    }

    attribute_map = {
        'type': 'type',
        'subtotal': 'subtotal',
        'detailed_breakdowns': 'detailedBreakdowns'
    }

    def __init__(self, type=None, subtotal=None, detailed_breakdowns=None):  # noqa: E501
        """ItemProceedsBreakdown - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._subtotal = None
        self._detailed_breakdowns = None
        self.discriminator = None

        self.type = type
        self.subtotal = subtotal
        if detailed_breakdowns is not None:
            self.detailed_breakdowns = detailed_breakdowns

    @property
    def type(self):
        """Gets the type of this ItemProceedsBreakdown.  # noqa: E501

        Category classification of the proceeds breakdown.   **Possible values**: `ITEM`, `SHIPPING`, `GIFT_WRAP`, `COD_FEE`, `OTHER`, `TAX`, `DISCOUNT`  # noqa: E501

        :return: The type of this ItemProceedsBreakdown.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ItemProceedsBreakdown.

        Category classification of the proceeds breakdown.   **Possible values**: `ITEM`, `SHIPPING`, `GIFT_WRAP`, `COD_FEE`, `OTHER`, `TAX`, `DISCOUNT`  # noqa: E501

        :param type: The type of this ItemProceedsBreakdown.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def subtotal(self):
        """Gets the subtotal of this ItemProceedsBreakdown.  # noqa: E501

        Monetary amount for the proceeds breakdown.  # noqa: E501

        :return: The subtotal of this ItemProceedsBreakdown.  # noqa: E501
        :rtype: Money
        """
        return self._subtotal

    @subtotal.setter
    def subtotal(self, subtotal):
        """Sets the subtotal of this ItemProceedsBreakdown.

        Monetary amount for the proceeds breakdown.  # noqa: E501

        :param subtotal: The subtotal of this ItemProceedsBreakdown.  # noqa: E501
        :type: Money
        """
        if subtotal is None:
            raise ValueError("Invalid value for `subtotal`, must not be `None`")  # noqa: E501

        self._subtotal = subtotal

    @property
    def detailed_breakdowns(self):
        """Gets the detailed_breakdowns of this ItemProceedsBreakdown.  # noqa: E501

        Further granular breakdown of the subtotal.  # noqa: E501

        :return: The detailed_breakdowns of this ItemProceedsBreakdown.  # noqa: E501
        :rtype: list[ItemProceedsDetailedBreakdown]
        """
        return self._detailed_breakdowns

    @detailed_breakdowns.setter
    def detailed_breakdowns(self, detailed_breakdowns):
        """Sets the detailed_breakdowns of this ItemProceedsBreakdown.

        Further granular breakdown of the subtotal.  # noqa: E501

        :param detailed_breakdowns: The detailed_breakdowns of this ItemProceedsBreakdown.  # noqa: E501
        :type: list[ItemProceedsDetailedBreakdown]
        """

        self._detailed_breakdowns = detailed_breakdowns

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ItemProceedsBreakdown, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemProceedsBreakdown):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
