# coding: utf-8

"""
    The Selling Partner API for Orders

    The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.  # noqa: E501

    OpenAPI spec version: 2026-01-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ItemShippingConstraints(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pallet_delivery': 'ConstraintType',
        'cash_on_delivery': 'ConstraintType',
        'signature_confirmation': 'ConstraintType',
        'recipient_identity_verification': 'ConstraintType',
        'recipient_age_verification': 'ConstraintType'
    }

    attribute_map = {
        'pallet_delivery': 'palletDelivery',
        'cash_on_delivery': 'cashOnDelivery',
        'signature_confirmation': 'signatureConfirmation',
        'recipient_identity_verification': 'recipientIdentityVerification',
        'recipient_age_verification': 'recipientAgeVerification'
    }

    def __init__(self, pallet_delivery=None, cash_on_delivery=None, signature_confirmation=None, recipient_identity_verification=None, recipient_age_verification=None):  # noqa: E501
        """ItemShippingConstraints - a model defined in Swagger"""  # noqa: E501

        self._pallet_delivery = None
        self._cash_on_delivery = None
        self._signature_confirmation = None
        self._recipient_identity_verification = None
        self._recipient_age_verification = None
        self.discriminator = None

        if pallet_delivery is not None:
            self.pallet_delivery = pallet_delivery
        if cash_on_delivery is not None:
            self.cash_on_delivery = cash_on_delivery
        if signature_confirmation is not None:
            self.signature_confirmation = signature_confirmation
        if recipient_identity_verification is not None:
            self.recipient_identity_verification = recipient_identity_verification
        if recipient_age_verification is not None:
            self.recipient_age_verification = recipient_age_verification

    @property
    def pallet_delivery(self):
        """Gets the pallet_delivery of this ItemShippingConstraints.  # noqa: E501

        The line item must be delivered by pallet.  # noqa: E501

        :return: The pallet_delivery of this ItemShippingConstraints.  # noqa: E501
        :rtype: ConstraintType
        """
        return self._pallet_delivery

    @pallet_delivery.setter
    def pallet_delivery(self, pallet_delivery):
        """Sets the pallet_delivery of this ItemShippingConstraints.

        The line item must be delivered by pallet.  # noqa: E501

        :param pallet_delivery: The pallet_delivery of this ItemShippingConstraints.  # noqa: E501
        :type: ConstraintType
        """

        self._pallet_delivery = pallet_delivery

    @property
    def cash_on_delivery(self):
        """Gets the cash_on_delivery of this ItemShippingConstraints.  # noqa: E501

        Payment must be collected from the customer at the time of delivery.  # noqa: E501

        :return: The cash_on_delivery of this ItemShippingConstraints.  # noqa: E501
        :rtype: ConstraintType
        """
        return self._cash_on_delivery

    @cash_on_delivery.setter
    def cash_on_delivery(self, cash_on_delivery):
        """Sets the cash_on_delivery of this ItemShippingConstraints.

        Payment must be collected from the customer at the time of delivery.  # noqa: E501

        :param cash_on_delivery: The cash_on_delivery of this ItemShippingConstraints.  # noqa: E501
        :type: ConstraintType
        """

        self._cash_on_delivery = cash_on_delivery

    @property
    def signature_confirmation(self):
        """Gets the signature_confirmation of this ItemShippingConstraints.  # noqa: E501

        The recipient of the line item must sign to confirm its delivery.  # noqa: E501

        :return: The signature_confirmation of this ItemShippingConstraints.  # noqa: E501
        :rtype: ConstraintType
        """
        return self._signature_confirmation

    @signature_confirmation.setter
    def signature_confirmation(self, signature_confirmation):
        """Sets the signature_confirmation of this ItemShippingConstraints.

        The recipient of the line item must sign to confirm its delivery.  # noqa: E501

        :param signature_confirmation: The signature_confirmation of this ItemShippingConstraints.  # noqa: E501
        :type: ConstraintType
        """

        self._signature_confirmation = signature_confirmation

    @property
    def recipient_identity_verification(self):
        """Gets the recipient_identity_verification of this ItemShippingConstraints.  # noqa: E501

        The person receiving the line item must be the same as the intended recipient of the order.  # noqa: E501

        :return: The recipient_identity_verification of this ItemShippingConstraints.  # noqa: E501
        :rtype: ConstraintType
        """
        return self._recipient_identity_verification

    @recipient_identity_verification.setter
    def recipient_identity_verification(self, recipient_identity_verification):
        """Sets the recipient_identity_verification of this ItemShippingConstraints.

        The person receiving the line item must be the same as the intended recipient of the order.  # noqa: E501

        :param recipient_identity_verification: The recipient_identity_verification of this ItemShippingConstraints.  # noqa: E501
        :type: ConstraintType
        """

        self._recipient_identity_verification = recipient_identity_verification

    @property
    def recipient_age_verification(self):
        """Gets the recipient_age_verification of this ItemShippingConstraints.  # noqa: E501

        The carrier must confirm that the recipient is of the legal age to receive the line item upon delivery.  # noqa: E501

        :return: The recipient_age_verification of this ItemShippingConstraints.  # noqa: E501
        :rtype: ConstraintType
        """
        return self._recipient_age_verification

    @recipient_age_verification.setter
    def recipient_age_verification(self, recipient_age_verification):
        """Sets the recipient_age_verification of this ItemShippingConstraints.

        The carrier must confirm that the recipient is of the legal age to receive the line item upon delivery.  # noqa: E501

        :param recipient_age_verification: The recipient_age_verification of this ItemShippingConstraints.  # noqa: E501
        :type: ConstraintType
        """

        self._recipient_age_verification = recipient_age_verification

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ItemShippingConstraints, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemShippingConstraints):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
