# coding: utf-8

"""
    The Selling Partner API for Orders

    The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.  # noqa: E501

    OpenAPI spec version: 2026-01-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ItemFulfillment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quantity_fulfilled': 'int',
        'quantity_unfulfilled': 'int',
        'picking': 'ItemPicking',
        'packing': 'ItemPacking',
        'shipping': 'ItemShipping'
    }

    attribute_map = {
        'quantity_fulfilled': 'quantityFulfilled',
        'quantity_unfulfilled': 'quantityUnfulfilled',
        'picking': 'picking',
        'packing': 'packing',
        'shipping': 'shipping'
    }

    def __init__(self, quantity_fulfilled=None, quantity_unfulfilled=None, picking=None, packing=None, shipping=None):  # noqa: E501
        """ItemFulfillment - a model defined in Swagger"""  # noqa: E501

        self._quantity_fulfilled = None
        self._quantity_unfulfilled = None
        self._picking = None
        self._packing = None
        self._shipping = None
        self.discriminator = None

        if quantity_fulfilled is not None:
            self.quantity_fulfilled = quantity_fulfilled
        if quantity_unfulfilled is not None:
            self.quantity_unfulfilled = quantity_unfulfilled
        if picking is not None:
            self.picking = picking
        if packing is not None:
            self.packing = packing
        if shipping is not None:
            self.shipping = shipping

    @property
    def quantity_fulfilled(self):
        """Gets the quantity_fulfilled of this ItemFulfillment.  # noqa: E501

        The number of units of this item that have been successfully processed and shipped.  # noqa: E501

        :return: The quantity_fulfilled of this ItemFulfillment.  # noqa: E501
        :rtype: int
        """
        return self._quantity_fulfilled

    @quantity_fulfilled.setter
    def quantity_fulfilled(self, quantity_fulfilled):
        """Sets the quantity_fulfilled of this ItemFulfillment.

        The number of units of this item that have been successfully processed and shipped.  # noqa: E501

        :param quantity_fulfilled: The quantity_fulfilled of this ItemFulfillment.  # noqa: E501
        :type: int
        """

        self._quantity_fulfilled = quantity_fulfilled

    @property
    def quantity_unfulfilled(self):
        """Gets the quantity_unfulfilled of this ItemFulfillment.  # noqa: E501

        The number of units of this item that remain to be processed and shipped.  # noqa: E501

        :return: The quantity_unfulfilled of this ItemFulfillment.  # noqa: E501
        :rtype: int
        """
        return self._quantity_unfulfilled

    @quantity_unfulfilled.setter
    def quantity_unfulfilled(self, quantity_unfulfilled):
        """Sets the quantity_unfulfilled of this ItemFulfillment.

        The number of units of this item that remain to be processed and shipped.  # noqa: E501

        :param quantity_unfulfilled: The quantity_unfulfilled of this ItemFulfillment.  # noqa: E501
        :type: int
        """

        self._quantity_unfulfilled = quantity_unfulfilled

    @property
    def picking(self):
        """Gets the picking of this ItemFulfillment.  # noqa: E501

        Information related to the warehouse picking process for this item.  # noqa: E501

        :return: The picking of this ItemFulfillment.  # noqa: E501
        :rtype: ItemPicking
        """
        return self._picking

    @picking.setter
    def picking(self, picking):
        """Sets the picking of this ItemFulfillment.

        Information related to the warehouse picking process for this item.  # noqa: E501

        :param picking: The picking of this ItemFulfillment.  # noqa: E501
        :type: ItemPicking
        """

        self._picking = picking

    @property
    def packing(self):
        """Gets the packing of this ItemFulfillment.  # noqa: E501

        Information related to the packaging process for this item.  # noqa: E501

        :return: The packing of this ItemFulfillment.  # noqa: E501
        :rtype: ItemPacking
        """
        return self._packing

    @packing.setter
    def packing(self, packing):
        """Sets the packing of this ItemFulfillment.

        Information related to the packaging process for this item.  # noqa: E501

        :param packing: The packing of this ItemFulfillment.  # noqa: E501
        :type: ItemPacking
        """

        self._packing = packing

    @property
    def shipping(self):
        """Gets the shipping of this ItemFulfillment.  # noqa: E501

        Information related to the shipping and delivery process for this item.  # noqa: E501

        :return: The shipping of this ItemFulfillment.  # noqa: E501
        :rtype: ItemShipping
        """
        return self._shipping

    @shipping.setter
    def shipping(self, shipping):
        """Sets the shipping of this ItemFulfillment.

        Information related to the shipping and delivery process for this item.  # noqa: E501

        :param shipping: The shipping of this ItemFulfillment.  # noqa: E501
        :type: ItemShipping
        """

        self._shipping = shipping

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ItemFulfillment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemFulfillment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
