# coding: utf-8

"""
    The Selling Partner API for Orders

    The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.  # noqa: E501

    OpenAPI spec version: 2026-01-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MerchantAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'address_line1': 'str',
        'address_line2': 'str',
        'address_line3': 'str',
        'city': 'str',
        'district_or_county': 'str',
        'state_or_region': 'str',
        'municipality': 'str',
        'postal_code': 'str',
        'country_code': 'str'
    }

    attribute_map = {
        'name': 'name',
        'address_line1': 'addressLine1',
        'address_line2': 'addressLine2',
        'address_line3': 'addressLine3',
        'city': 'city',
        'district_or_county': 'districtOrCounty',
        'state_or_region': 'stateOrRegion',
        'municipality': 'municipality',
        'postal_code': 'postalCode',
        'country_code': 'countryCode'
    }

    def __init__(self, name=None, address_line1=None, address_line2=None, address_line3=None, city=None, district_or_county=None, state_or_region=None, municipality=None, postal_code=None, country_code=None):  # noqa: E501
        """MerchantAddress - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._address_line1 = None
        self._address_line2 = None
        self._address_line3 = None
        self._city = None
        self._district_or_county = None
        self._state_or_region = None
        self._municipality = None
        self._postal_code = None
        self._country_code = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if address_line1 is not None:
            self.address_line1 = address_line1
        if address_line2 is not None:
            self.address_line2 = address_line2
        if address_line3 is not None:
            self.address_line3 = address_line3
        if city is not None:
            self.city = city
        if district_or_county is not None:
            self.district_or_county = district_or_county
        if state_or_region is not None:
            self.state_or_region = state_or_region
        if municipality is not None:
            self.municipality = municipality
        if postal_code is not None:
            self.postal_code = postal_code
        if country_code is not None:
            self.country_code = country_code

    @property
    def name(self):
        """Gets the name of this MerchantAddress.  # noqa: E501

        The name of the business or facility at this address.  # noqa: E501

        :return: The name of this MerchantAddress.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MerchantAddress.

        The name of the business or facility at this address.  # noqa: E501

        :param name: The name of this MerchantAddress.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def address_line1(self):
        """Gets the address_line1 of this MerchantAddress.  # noqa: E501

        The primary street address of the merchant's location.  # noqa: E501

        :return: The address_line1 of this MerchantAddress.  # noqa: E501
        :rtype: str
        """
        return self._address_line1

    @address_line1.setter
    def address_line1(self, address_line1):
        """Sets the address_line1 of this MerchantAddress.

        The primary street address of the merchant's location.  # noqa: E501

        :param address_line1: The address_line1 of this MerchantAddress.  # noqa: E501
        :type: str
        """

        self._address_line1 = address_line1

    @property
    def address_line2(self):
        """Gets the address_line2 of this MerchantAddress.  # noqa: E501

        Additional address information.  # noqa: E501

        :return: The address_line2 of this MerchantAddress.  # noqa: E501
        :rtype: str
        """
        return self._address_line2

    @address_line2.setter
    def address_line2(self, address_line2):
        """Sets the address_line2 of this MerchantAddress.

        Additional address information.  # noqa: E501

        :param address_line2: The address_line2 of this MerchantAddress.  # noqa: E501
        :type: str
        """

        self._address_line2 = address_line2

    @property
    def address_line3(self):
        """Gets the address_line3 of this MerchantAddress.  # noqa: E501

        Additional address information.  # noqa: E501

        :return: The address_line3 of this MerchantAddress.  # noqa: E501
        :rtype: str
        """
        return self._address_line3

    @address_line3.setter
    def address_line3(self, address_line3):
        """Sets the address_line3 of this MerchantAddress.

        Additional address information.  # noqa: E501

        :param address_line3: The address_line3 of this MerchantAddress.  # noqa: E501
        :type: str
        """

        self._address_line3 = address_line3

    @property
    def city(self):
        """Gets the city of this MerchantAddress.  # noqa: E501

        The city of the address.  # noqa: E501

        :return: The city of this MerchantAddress.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this MerchantAddress.

        The city of the address.  # noqa: E501

        :param city: The city of this MerchantAddress.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def district_or_county(self):
        """Gets the district_or_county of this MerchantAddress.  # noqa: E501

        The district or county of the address.  # noqa: E501

        :return: The district_or_county of this MerchantAddress.  # noqa: E501
        :rtype: str
        """
        return self._district_or_county

    @district_or_county.setter
    def district_or_county(self, district_or_county):
        """Sets the district_or_county of this MerchantAddress.

        The district or county of the address.  # noqa: E501

        :param district_or_county: The district_or_county of this MerchantAddress.  # noqa: E501
        :type: str
        """

        self._district_or_county = district_or_county

    @property
    def state_or_region(self):
        """Gets the state_or_region of this MerchantAddress.  # noqa: E501

        The state, province, or region of the address.  # noqa: E501

        :return: The state_or_region of this MerchantAddress.  # noqa: E501
        :rtype: str
        """
        return self._state_or_region

    @state_or_region.setter
    def state_or_region(self, state_or_region):
        """Sets the state_or_region of this MerchantAddress.

        The state, province, or region of the address.  # noqa: E501

        :param state_or_region: The state_or_region of this MerchantAddress.  # noqa: E501
        :type: str
        """

        self._state_or_region = state_or_region

    @property
    def municipality(self):
        """Gets the municipality of this MerchantAddress.  # noqa: E501

        The municipality of the address.  # noqa: E501

        :return: The municipality of this MerchantAddress.  # noqa: E501
        :rtype: str
        """
        return self._municipality

    @municipality.setter
    def municipality(self, municipality):
        """Sets the municipality of this MerchantAddress.

        The municipality of the address.  # noqa: E501

        :param municipality: The municipality of this MerchantAddress.  # noqa: E501
        :type: str
        """

        self._municipality = municipality

    @property
    def postal_code(self):
        """Gets the postal_code of this MerchantAddress.  # noqa: E501

        The postal code or ZIP code of the address.  # noqa: E501

        :return: The postal_code of this MerchantAddress.  # noqa: E501
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this MerchantAddress.

        The postal code or ZIP code of the address.  # noqa: E501

        :param postal_code: The postal_code of this MerchantAddress.  # noqa: E501
        :type: str
        """

        self._postal_code = postal_code

    @property
    def country_code(self):
        """Gets the country_code of this MerchantAddress.  # noqa: E501

        The two-letter country code for the address, in ISO 3166-1 format.  # noqa: E501

        :return: The country_code of this MerchantAddress.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this MerchantAddress.

        The two-letter country code for the address, in ISO 3166-1 format.  # noqa: E501

        :param country_code: The country_code of this MerchantAddress.  # noqa: E501
        :type: str
        """

        self._country_code = country_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MerchantAddress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MerchantAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
