# coding: utf-8

"""
    The Selling Partner API for Orders

    The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.  # noqa: E501

    OpenAPI spec version: 2026-01-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OrderPackage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'package_reference_id': 'str',
        'created_time': 'datetime',
        'package_status': 'PackageStatus',
        'carrier': 'str',
        'ship_time': 'datetime',
        'shipping_service': 'str',
        'tracking_number': 'str',
        'ship_from_address': 'MerchantAddress',
        'package_items': 'list[PackageItem]'
    }

    attribute_map = {
        'package_reference_id': 'packageReferenceId',
        'created_time': 'createdTime',
        'package_status': 'packageStatus',
        'carrier': 'carrier',
        'ship_time': 'shipTime',
        'shipping_service': 'shippingService',
        'tracking_number': 'trackingNumber',
        'ship_from_address': 'shipFromAddress',
        'package_items': 'packageItems'
    }

    def __init__(self, package_reference_id=None, created_time=None, package_status=None, carrier=None, ship_time=None, shipping_service=None, tracking_number=None, ship_from_address=None, package_items=None):  # noqa: E501
        """OrderPackage - a model defined in Swagger"""  # noqa: E501

        self._package_reference_id = None
        self._created_time = None
        self._package_status = None
        self._carrier = None
        self._ship_time = None
        self._shipping_service = None
        self._tracking_number = None
        self._ship_from_address = None
        self._package_items = None
        self.discriminator = None

        self.package_reference_id = package_reference_id
        if created_time is not None:
            self.created_time = created_time
        if package_status is not None:
            self.package_status = package_status
        if carrier is not None:
            self.carrier = carrier
        if ship_time is not None:
            self.ship_time = ship_time
        if shipping_service is not None:
            self.shipping_service = shipping_service
        if tracking_number is not None:
            self.tracking_number = tracking_number
        if ship_from_address is not None:
            self.ship_from_address = ship_from_address
        if package_items is not None:
            self.package_items = package_items

    @property
    def package_reference_id(self):
        """Gets the package_reference_id of this OrderPackage.  # noqa: E501

        A unique identifier for this package within the context of the order.  # noqa: E501

        :return: The package_reference_id of this OrderPackage.  # noqa: E501
        :rtype: str
        """
        return self._package_reference_id

    @package_reference_id.setter
    def package_reference_id(self, package_reference_id):
        """Sets the package_reference_id of this OrderPackage.

        A unique identifier for this package within the context of the order.  # noqa: E501

        :param package_reference_id: The package_reference_id of this OrderPackage.  # noqa: E501
        :type: str
        """
        if package_reference_id is None:
            raise ValueError("Invalid value for `package_reference_id`, must not be `None`")  # noqa: E501

        self._package_reference_id = package_reference_id

    @property
    def created_time(self):
        """Gets the created_time of this OrderPackage.  # noqa: E501

        The exact time when this shipping package was created and prepared for shipment. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.  # noqa: E501

        :return: The created_time of this OrderPackage.  # noqa: E501
        :rtype: datetime
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this OrderPackage.

        The exact time when this shipping package was created and prepared for shipment. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.  # noqa: E501

        :param created_time: The created_time of this OrderPackage.  # noqa: E501
        :type: datetime
        """

        self._created_time = created_time

    @property
    def package_status(self):
        """Gets the package_status of this OrderPackage.  # noqa: E501

        The current status of this package.  # noqa: E501

        :return: The package_status of this OrderPackage.  # noqa: E501
        :rtype: PackageStatus
        """
        return self._package_status

    @package_status.setter
    def package_status(self, package_status):
        """Sets the package_status of this OrderPackage.

        The current status of this package.  # noqa: E501

        :param package_status: The package_status of this OrderPackage.  # noqa: E501
        :type: PackageStatus
        """

        self._package_status = package_status

    @property
    def carrier(self):
        """Gets the carrier of this OrderPackage.  # noqa: E501

        The carrier responsible for transporting this package to the customer.  # noqa: E501

        :return: The carrier of this OrderPackage.  # noqa: E501
        :rtype: str
        """
        return self._carrier

    @carrier.setter
    def carrier(self, carrier):
        """Sets the carrier of this OrderPackage.

        The carrier responsible for transporting this package to the customer.  # noqa: E501

        :param carrier: The carrier of this OrderPackage.  # noqa: E501
        :type: str
        """

        self._carrier = carrier

    @property
    def ship_time(self):
        """Gets the ship_time of this OrderPackage.  # noqa: E501

        The exact time when this package was handed over to the carrier and began its journey to the customer. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.  # noqa: E501

        :return: The ship_time of this OrderPackage.  # noqa: E501
        :rtype: datetime
        """
        return self._ship_time

    @ship_time.setter
    def ship_time(self, ship_time):
        """Sets the ship_time of this OrderPackage.

        The exact time when this package was handed over to the carrier and began its journey to the customer. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.  # noqa: E501

        :param ship_time: The ship_time of this OrderPackage.  # noqa: E501
        :type: datetime
        """

        self._ship_time = ship_time

    @property
    def shipping_service(self):
        """Gets the shipping_service of this OrderPackage.  # noqa: E501

        The specific shipping method or service used for delivering this package.  # noqa: E501

        :return: The shipping_service of this OrderPackage.  # noqa: E501
        :rtype: str
        """
        return self._shipping_service

    @shipping_service.setter
    def shipping_service(self, shipping_service):
        """Sets the shipping_service of this OrderPackage.

        The specific shipping method or service used for delivering this package.  # noqa: E501

        :param shipping_service: The shipping_service of this OrderPackage.  # noqa: E501
        :type: str
        """

        self._shipping_service = shipping_service

    @property
    def tracking_number(self):
        """Gets the tracking_number of this OrderPackage.  # noqa: E501

        The carrier-provided tracking number that customers can use to monitor the package's delivery progress.  # noqa: E501

        :return: The tracking_number of this OrderPackage.  # noqa: E501
        :rtype: str
        """
        return self._tracking_number

    @tracking_number.setter
    def tracking_number(self, tracking_number):
        """Sets the tracking_number of this OrderPackage.

        The carrier-provided tracking number that customers can use to monitor the package's delivery progress.  # noqa: E501

        :param tracking_number: The tracking_number of this OrderPackage.  # noqa: E501
        :type: str
        """

        self._tracking_number = tracking_number

    @property
    def ship_from_address(self):
        """Gets the ship_from_address of this OrderPackage.  # noqa: E501

        The physical address from which this package was shipped, typically the merchant's warehouse or fulfillment center.  # noqa: E501

        :return: The ship_from_address of this OrderPackage.  # noqa: E501
        :rtype: MerchantAddress
        """
        return self._ship_from_address

    @ship_from_address.setter
    def ship_from_address(self, ship_from_address):
        """Sets the ship_from_address of this OrderPackage.

        The physical address from which this package was shipped, typically the merchant's warehouse or fulfillment center.  # noqa: E501

        :param ship_from_address: The ship_from_address of this OrderPackage.  # noqa: E501
        :type: MerchantAddress
        """

        self._ship_from_address = ship_from_address

    @property
    def package_items(self):
        """Gets the package_items of this OrderPackage.  # noqa: E501

        A list of all order items included in this specific package.  # noqa: E501

        :return: The package_items of this OrderPackage.  # noqa: E501
        :rtype: list[PackageItem]
        """
        return self._package_items

    @package_items.setter
    def package_items(self, package_items):
        """Sets the package_items of this OrderPackage.

        A list of all order items included in this specific package.  # noqa: E501

        :param package_items: The package_items of this OrderPackage.  # noqa: E501
        :type: list[PackageItem]
        """

        self._package_items = package_items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderPackage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderPackage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
