# coding: utf-8

"""
    The Selling Partner API for Orders

    The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.  # noqa: E501

    OpenAPI spec version: 2026-01-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OrderTaxRegistration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_type': 'str',
        'legal_name': 'str',
        'tax_registration_type': 'str',
        'tax_registration_number': 'str',
        'tax_registration_address': 'CustomerAddress',
        'tax_registration_attributes': 'list[TaxRegistrationAttribute]'
    }

    attribute_map = {
        'entity_type': 'entityType',
        'legal_name': 'legalName',
        'tax_registration_type': 'taxRegistrationType',
        'tax_registration_number': 'taxRegistrationNumber',
        'tax_registration_address': 'taxRegistrationAddress',
        'tax_registration_attributes': 'taxRegistrationAttributes'
    }

    def __init__(self, entity_type=None, legal_name=None, tax_registration_type=None, tax_registration_number=None, tax_registration_address=None, tax_registration_attributes=None):  # noqa: E501
        """OrderTaxRegistration - a model defined in Swagger"""  # noqa: E501

        self._entity_type = None
        self._legal_name = None
        self._tax_registration_type = None
        self._tax_registration_number = None
        self._tax_registration_address = None
        self._tax_registration_attributes = None
        self.discriminator = None

        if entity_type is not None:
            self.entity_type = entity_type
        if legal_name is not None:
            self.legal_name = legal_name
        if tax_registration_type is not None:
            self.tax_registration_type = tax_registration_type
        if tax_registration_number is not None:
            self.tax_registration_number = tax_registration_number
        if tax_registration_address is not None:
            self.tax_registration_address = tax_registration_address
        if tax_registration_attributes is not None:
            self.tax_registration_attributes = tax_registration_attributes

    @property
    def entity_type(self):
        """Gets the entity_type of this OrderTaxRegistration.  # noqa: E501

        The type of entity that the tax registration belongs to.  **Possible values**: - `BUYER` (Indicates that this is the buyer's tax registration information) - `MERCHANT` (Indicates that this is the merchant's tax registration information) - `MARKETPLACE` (Indicates that this is the marketplace's tax registration information)  # noqa: E501

        :return: The entity_type of this OrderTaxRegistration.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this OrderTaxRegistration.

        The type of entity that the tax registration belongs to.  **Possible values**: - `BUYER` (Indicates that this is the buyer's tax registration information) - `MERCHANT` (Indicates that this is the merchant's tax registration information) - `MARKETPLACE` (Indicates that this is the marketplace's tax registration information)  # noqa: E501

        :param entity_type: The entity_type of this OrderTaxRegistration.  # noqa: E501
        :type: str
        """

        self._entity_type = entity_type

    @property
    def legal_name(self):
        """Gets the legal_name of this OrderTaxRegistration.  # noqa: E501

        The legal name associated with the tax registration.  # noqa: E501

        :return: The legal_name of this OrderTaxRegistration.  # noqa: E501
        :rtype: str
        """
        return self._legal_name

    @legal_name.setter
    def legal_name(self, legal_name):
        """Sets the legal_name of this OrderTaxRegistration.

        The legal name associated with the tax registration.  # noqa: E501

        :param legal_name: The legal_name of this OrderTaxRegistration.  # noqa: E501
        :type: str
        """

        self._legal_name = legal_name

    @property
    def tax_registration_type(self):
        """Gets the tax_registration_type of this OrderTaxRegistration.  # noqa: E501

        The type of the tax registration number.  **Possible values**: `BUSINESS`, `VAT`, `CST`, `CPF`, `CNPJ`  # noqa: E501

        :return: The tax_registration_type of this OrderTaxRegistration.  # noqa: E501
        :rtype: str
        """
        return self._tax_registration_type

    @tax_registration_type.setter
    def tax_registration_type(self, tax_registration_type):
        """Sets the tax_registration_type of this OrderTaxRegistration.

        The type of the tax registration number.  **Possible values**: `BUSINESS`, `VAT`, `CST`, `CPF`, `CNPJ`  # noqa: E501

        :param tax_registration_type: The tax_registration_type of this OrderTaxRegistration.  # noqa: E501
        :type: str
        """

        self._tax_registration_type = tax_registration_type

    @property
    def tax_registration_number(self):
        """Gets the tax_registration_number of this OrderTaxRegistration.  # noqa: E501

        The tax registration number that identifies the entity for tax purposes.  # noqa: E501

        :return: The tax_registration_number of this OrderTaxRegistration.  # noqa: E501
        :rtype: str
        """
        return self._tax_registration_number

    @tax_registration_number.setter
    def tax_registration_number(self, tax_registration_number):
        """Sets the tax_registration_number of this OrderTaxRegistration.

        The tax registration number that identifies the entity for tax purposes.  # noqa: E501

        :param tax_registration_number: The tax_registration_number of this OrderTaxRegistration.  # noqa: E501
        :type: str
        """

        self._tax_registration_number = tax_registration_number

    @property
    def tax_registration_address(self):
        """Gets the tax_registration_address of this OrderTaxRegistration.  # noqa: E501

        The address associated with the tax registration.  # noqa: E501

        :return: The tax_registration_address of this OrderTaxRegistration.  # noqa: E501
        :rtype: CustomerAddress
        """
        return self._tax_registration_address

    @tax_registration_address.setter
    def tax_registration_address(self, tax_registration_address):
        """Sets the tax_registration_address of this OrderTaxRegistration.

        The address associated with the tax registration.  # noqa: E501

        :param tax_registration_address: The tax_registration_address of this OrderTaxRegistration.  # noqa: E501
        :type: CustomerAddress
        """

        self._tax_registration_address = tax_registration_address

    @property
    def tax_registration_attributes(self):
        """Gets the tax_registration_attributes of this OrderTaxRegistration.  # noqa: E501

        Additional attributes related to the tax registration.  # noqa: E501

        :return: The tax_registration_attributes of this OrderTaxRegistration.  # noqa: E501
        :rtype: list[TaxRegistrationAttribute]
        """
        return self._tax_registration_attributes

    @tax_registration_attributes.setter
    def tax_registration_attributes(self, tax_registration_attributes):
        """Sets the tax_registration_attributes of this OrderTaxRegistration.

        Additional attributes related to the tax registration.  # noqa: E501

        :param tax_registration_attributes: The tax_registration_attributes of this OrderTaxRegistration.  # noqa: E501
        :type: list[TaxRegistrationAttribute]
        """

        self._tax_registration_attributes = tax_registration_attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderTaxRegistration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderTaxRegistration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
