# coding: utf-8

"""
    The Selling Partner API for Orders

    The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.  # noqa: E501

    OpenAPI spec version: 2026-01-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PreferredDeliveryTime(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'business_hours': 'list[BusinessHour]',
        'exception_dates': 'list[ExceptionDate]'
    }

    attribute_map = {
        'business_hours': 'businessHours',
        'exception_dates': 'exceptionDates'
    }

    def __init__(self, business_hours=None, exception_dates=None):  # noqa: E501
        """PreferredDeliveryTime - a model defined in Swagger"""  # noqa: E501

        self._business_hours = None
        self._exception_dates = None
        self.discriminator = None

        if business_hours is not None:
            self.business_hours = business_hours
        if exception_dates is not None:
            self.exception_dates = exception_dates

    @property
    def business_hours(self):
        """Gets the business_hours of this PreferredDeliveryTime.  # noqa: E501

        Business hours when the business is open for deliveries.  # noqa: E501

        :return: The business_hours of this PreferredDeliveryTime.  # noqa: E501
        :rtype: list[BusinessHour]
        """
        return self._business_hours

    @business_hours.setter
    def business_hours(self, business_hours):
        """Sets the business_hours of this PreferredDeliveryTime.

        Business hours when the business is open for deliveries.  # noqa: E501

        :param business_hours: The business_hours of this PreferredDeliveryTime.  # noqa: E501
        :type: list[BusinessHour]
        """

        self._business_hours = business_hours

    @property
    def exception_dates(self):
        """Gets the exception_dates of this PreferredDeliveryTime.  # noqa: E501

        Specific dates within the next 30 days when normal business hours do not apply.  # noqa: E501

        :return: The exception_dates of this PreferredDeliveryTime.  # noqa: E501
        :rtype: list[ExceptionDate]
        """
        return self._exception_dates

    @exception_dates.setter
    def exception_dates(self, exception_dates):
        """Sets the exception_dates of this PreferredDeliveryTime.

        Specific dates within the next 30 days when normal business hours do not apply.  # noqa: E501

        :param exception_dates: The exception_dates of this PreferredDeliveryTime.  # noqa: E501
        :type: list[ExceptionDate]
        """

        self._exception_dates = exception_dates

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PreferredDeliveryTime, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PreferredDeliveryTime):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
