# coding: utf-8

"""
    Selling Partner API for Replenishment

    The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.  # noqa: E501

    OpenAPI spec version: 2022-11-07
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_offer_metrics_request import ListOfferMetricsRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestListOfferMetricsRequest(unittest.TestCase):
    """ListOfferMetricsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListOfferMetricsRequest(self):
        """Test ListOfferMetricsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_offer_metrics_request.ListOfferMetricsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
